import {
  createContext,
  useContext,
  useState,
  useEffect,
  ReactNode,
} from "react";

export type Language = "en" | "ar";
export type Direction = "ltr" | "rtl";

interface LanguageContextType {
  language: Language;
  direction: Direction;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined,
);

// Translation dictionary
const translations = {
  en: {
    // Navbar
    "nav.dashboard": "Dashboard",
    "nav.projects": "Projects",
    "nav.requirements": "Analysis Requirements",
    "nav.developmentRequirements": "Development Requirements",
    "nav.taskPlan": "Task Plan",
    "nav.users": "Users",
    "nav.timeline": "Timeline",
    "nav.tasks": "Tasks",
    "nav.departments": "Departments",
    "nav.reports": "Reports",
    "nav.newProject": "New Project",
    "nav.notifications": "Notifications",
    "nav.notificationsTitle": "Notifications",
    "nav.search": "Search projects, tasks, people...",
    "nav.searchModal": "Search",
    "nav.searchPlaceholder": "Search projects, tasks, team members...",
    "nav.searchResults": "Search results for",
    "nav.searchPrompt":
      "Start typing to search projects, tasks, and team members...",
    "nav.noNotifications": "No notifications",
    "nav.markAllRead": "Mark all as read",

    // Urgent Notifications
    "notifications.urgent": "Urgent",
    "notifications.minimize": "Minimize",
    "notifications.markAsRead": "Mark as read",
    "dashboard.urgentNotifications": "Urgent Notifications",
    "dashboard.updates": "Updates",
    "dashboard.projectPipeline": "Project Pipeline",

    // Project Pipeline
    "pipeline.planning": "Planning",
    "pipeline.inProgress": "In Progress",
    "pipeline.completed": "Completed",
    "pipeline.initiatePlanning": "Initiate Planning",
    "pipeline.reviewRequirements": "Review Requirements",
    "pipeline.resourceAllocation": "Resource Allocation",
    "pipeline.assignTeamMembers": "Assign Team Members",
    "pipeline.activeDevelopment": "Active Development",
    "pipeline.codingPhase": "Coding Phase",
    "pipeline.testing": "Testing",
    "pipeline.qualityAssurance": "Quality Assurance",
    "pipeline.deployment": "Deployment",
    "pipeline.liveProduction": "Live Production",
    "pipeline.maintenance": "Maintenance",
    "pipeline.ongoingSupport": "Ongoing Support",
    "pipeline.noProjects": "No projects in this stage",

    // Calendar
    "calendar.title": "Calendar",
  "calendar.previousMonth": "Previous month",
  "calendar.nextMonth": "Next month",
  "calendar.month": "Month",
    "calendar.week": "Week",
    "calendar.day": "Day",
    "calendar.today": "Today",
    "calendar.addEvent": "Add Event",
    "calendar.overview": "Overview",
    "calendar.upcoming": "Upcoming",
    "calendar.overdue": "Overdue",
    "calendar.completedWeek": "Completed This Week",
    "calendar.critical": "Critical Deadlines",
    "calendar.upcomingEvents": "Upcoming Events",
    "calendar.overdueEvents": "Overdue Events",
    "calendar.noEvents": "No events found",
    "calendar.noUpcoming": "No upcoming events",
    "calendar.description": "Description",
    "calendar.startDate": "Start Date",
    "calendar.endDate": "End Date",
    "calendar.startDateTime": "Start Date & Time",
    "calendar.endDateTime": "End Date & Time",
    "calendar.startTime": "Start Time",
    "calendar.endTime": "End Time",
    "calendar.status": "Status",
    "calendar.priority": "Priority",
    "calendar.location": "Location",
    "calendar.editEvent": "Edit Event",
    "calendar.sun": "Sun",
    "calendar.mon": "Mon",
    "calendar.tue": "Tue",
    "calendar.wed": "Wed",
    "calendar.thu": "Thu",
    "calendar.fri": "Fri",
    "calendar.sat": "Sat",
    "calendar.type": "Type",
    "calendar.type.project": "Project",
    "calendar.type.requirement": "Requirement",
    "calendar.type.meeting": "Meeting",
    "calendar.type.deadline": "Deadline",
    "calendar.type.milestone": "Milestone",
    "calendar.status.upcoming": "Upcoming",
    "calendar.status.in-progress": "In Progress",
    "calendar.status.completed": "Completed",
    "calendar.status.overdue": "Overdue",
    "calendar.priority.low": "Low",
    "calendar.priority.medium": "Medium",
    "calendar.priority.high": "High",
    "calendar.priority.critical": "Critical",
    "calendar.eventTitle": "Title",
    "calendar.titlePlaceholder": "Enter event title",
    "calendar.descriptionPlaceholder": "Enter event description",
    "calendar.locationPlaceholder": "Enter location",
    "calendar.allDay": "All Day",

    // Calendar Filters
    "calendar.search": "Search",
    "calendar.searchPlaceholder": "Search events...",
    "calendar.allTypes": "All Types",
    "calendar.allPriorities": "All Priorities",
    "calendar.clearFilters": "Clear Filters",
    "calendar.eventTypes.meeting": "Meeting",
    "calendar.eventTypes.task": "Task",
    "calendar.eventTypes.deadline": "Deadline",
    "calendar.eventTypes.project": "Project",
    "calendar.eventTypes.requirement": "Requirement",
    "calendar.priorities.low": "Low",
    "calendar.priorities.medium": "Medium",
    "calendar.priorities.high": "High",
    "calendar.priorities.urgent": "Urgent",

    // Calendar Color Legend
    "calendar.colorLegend": "Color Legend",
    "calendar.visualEffects": "Visual Effects",
    "calendar.criticalShadow": "Critical Priority",
    "calendar.priorityBorder": "Priority Border",

    // Calendar Validation Messages
    "calendar.validation.titleRequired": "Event title is required",
    "calendar.validation.startDateRequired": "Start date is required",
    "calendar.validation.startTimeRequired": "Start time is required",
    "calendar.validation.endDateBeforeStart":
      "End date cannot be before start date",
    "calendar.validation.endTimeBeforeStart":
      "End time must be after start time for same-day events",
    "calendar.validation.saveFailed": "Failed to save event. Please try again.",

    // Common
    "common.owner": "Owner",
    "common.lastActivity": "Last Activity",
    "common.tryAgainLater": "Please try again later",
    "common.projectManagement": "Project Management",

    // Requirement Overview
    "dashboard.requirementOverview": "Requirement Overview",
    "requirements.ongoing": "Ongoing Requirements",
    "requirements.active": "Active Requirements",
    "requirements.pendingApprovals": "Pending Approvals",

    // Common Date References
    "common.today": "Today",
    "common.yesterday": "Yesterday",

    // Global Search
    "search.title": "Global Search",
    "search.placeholder": "Search projects, users, timelines, tasks...",
    "search.filters": "Filters",
    "search.clearFilters": "Clear Filters",
    "search.type": "Type",
    "search.status": "Status",
    "search.department": "Department",
    "search.selectType": "Select types",
    "search.selectStatus": "Select status",
    "search.selectDepartment": "Select departments",
    "search.noResults": "No results found",
    "search.tryDifferent": "Try a different search term or adjust your filters",
    "search.recent": "Recent Searches",
    "search.clear": "Clear",
    "search.suggestions": "Suggestions",
    "search.startTyping": "Start typing to search",
    "search.searchDescription":
      "Search across projects, users, timelines, tasks and more",
    "search.resultsCount": 'Found {count} results for "{query}"',

    // User Menu
    "user.account": "Account",
    "user.workspace": "Workspace",
    "user.profile": "Profile",
    "user.settings": "Settings",
    "user.departmentManagement": "Department Management",
    "user.billing": "Billing",
    "user.logout": "Log Out",
    "user.profileDesc": "View and edit your profile",
    "user.settingsDesc": "Account preferences",
    "user.departmentsDesc": "Manage department members",
    "user.billingDesc": "View billing information",
    "user.logoutDesc": "Sign out of your account",
    "user.administration": "Administration",
    "user.userManagement": "User Management",
    "user.userManagementDesc": "Manage users and permissions",
    "user.systemSettings": "System Settings",
    "user.systemSettingsDesc": "Configure system settings",
    "user.loading": "Loading user data...",
    "user.loadingProfile": "Loading user profile...",

    // Dashboard
    "dashboard.title": "Project Management Dashboard",
    "dashboard.subtitle": "Track and manage your projects efficiently",
    "dashboard.projectsUnderReview": "Projects Under Review",
    "dashboard.requiredAttention": "Required Four Personnel Attention",
    "dashboard.overdueTasks": "Overdue Tasks",
    "dashboard.dueDatesPassedAction": "Due dates passed, action required",
    "dashboard.changeBehindSchedule": "Change Behind Schedule",
    "dashboard.viewCurrentSchedule": "View the current schedule",
    "dashboard.underReview": "Under Review",
    "dashboard.analysisInProgress": "Analysis in Progress",
    "dashboard.awaitingDev": "Awaiting Dev",
    "dashboard.teamWorkload": "Team Workload",
    "dashboard.teamWorkloadPerformance": "Team Workload & Performance",
    "dashboard.viewAllProjects": "View All Projects",
    "dashboard.teamName": "Team Name",
    "dashboard.progressMapped": "Progress Mapped",
    "dashboard.progressCompleted": "Progress Completed | Per week |",
    "dashboard.avgTaskThroughput": "Avg Task Throughput | Per |",
    "dashboard.nexus": "Nexus",
    "dashboard.managerTeams": "Manager Teams",
    "dashboard.noManagerTeamsData": "No manager teams data available",
    "dashboard.requirementsOverview": "Requirements Overview",
    "dashboard.newRequirements": "New Requirements",
    "dashboard.changeRequests": "Change Requests",
    "dashboard.totalActiveRequirements": "Total Active Requirements",
    "dashboard.pendingApproval": "Pending Approval",
    "dashboard.viewAllRequirementLog": "View All Requirement Log",
    "dashboard.newProject": "New Project",
    "dashboard.activeProjects": "Active Projects",
    "dashboard.totalTasks": "Total Tasks",
    "dashboard.inProgress": "In Progress",
    "dashboard.overdue": "Overdue",
    "dashboard.importData": "Import Data",
    "dashboard.viewDetails": "View Details",
    "dashboard.recentTasks": "Recent Tasks",
    "dashboard.tasks": "Tasks",
    "dashboard.due": "Due",
    "dashboard.progress": "Progress",
    "dashboard.teamMembers": "Team Members",
    "dashboard.task": "Task",
    "dashboard.assignee": "Assignee",
    "dashboard.status": "Status",
    "dashboard.priority": "Priority",
    "dashboard.dueDate": "Due Date",
    "dashboard.assignedTo": "Assigned to",

    // Team Workload
    "team.member": "Team Member",
    "team.department": "Department",
    "team.total": "Total",
    "team.inProgress": "In Progress",
    "team.completed": "Completed",
    "team.performance": "Performance",
    "team.busy": "Busy",
    "team.available": "Available",
    "team.busyUntilToday": "Busy until later today",
    "team.busyUntilTomorrow": "Busy until tomorrow",
    "team.busyUntilDays": "Busy for {days} more days",
    "team.busyUntilDate": "Busy until {date}",
    "team.search": "Search",
    "team.searchPlaceholder": "Search team members...",
    "team.allDepartments": "All Departments",
    "team.busyStatus": "Status",
    "team.allStatuses": "All Statuses",
    "team.performanceRange": "Performance",
    "team.allPerformance": "All Performance",
    "team.excellent": "Excellent",
    "team.good": "Good",
    "team.average": "Average",
    "team.poor": "Poor",
    "team.filtered": "filtered",
    "team.clearFilters": "Clear Filters",
    "team.noFilterResults": "No team members match the current filters",
    "team.members": "members",
    "team.busyUntil": "Busy until {date}",

    // Project Status
    "status.active": "Active",
    "status.completed": "Completed",
    "status.onHold": "On Hold",
    "status.todo": "To Do",
    "status.inProgress": "In Progress",

    // Priority
    "priority.high": "High",
    "priority.medium": "Medium",
    "priority.low": "Low",

    // Common
    "common.total": "Total",
    "common.retry": "Retry",
    "common.actions": "Actions",
    "common.due": "Due",
    "common.tasks": "tasks",
    "common.progress": "Progress",
    "common.close": "Close",
    "common.edit": "Edit",
    "common.view": "View",
    "common.save": "Save",
    "common.refresh": "Refresh",
    "common.editProject": "Edit Project",
    "common.cancel": "Cancel",
    "common.select": "Select",
    "common.clear": "Clear",
    "common.search": "Search",
    "common.delete": "Delete",
    "common.remove": "Remove",
    "common.add": "Add",
    "common.create": "Create",
    "common.update": "Update",
    "common.error": "Error",
    "common.all": "All",
    "common.inactive": "Inactive",
    "common.show": "Show",
    "common.loading": "Loading...",
    "common.searching": "Searching",
    "common.pleaseWait": "Please wait...",
    "common.noDataFound": "No data found",
    "common.unexpectedError": "An unexpected error occurred",

    // Table
    "table.noData": "No data available",

    // Pagination
    "pagination.showing": "Showing",
    "pagination.to": "to",
    "pagination.of": "of",
    "pagination.items": "items",
    "pagination.page": "Page",
    "pagination.perPage": "per page",
    "pagination.goTo": "Go to page",
    "pagination.previous": "Previous",
    "pagination.next": "Next",
    "pagination.first": "First",
    "pagination.last": "Last",
    "pagination.loading": "Loading page...",
    "pagination.loadingPage": "Loading page {page}...",

    // Projects
    "projects.title": "Projects Management",
    "projects.subtitle": "Manage all organizational applications and projects",
    "projects.newProject": "New Project",
    "projects.importProjects": "Import Projects",
    "projects.exportData": "Export Data",
    "projects.totalProjects": "Total Projects",
    "projects.underStudy": "Under Study",
    "projects.underDevelopment": "Under Development",
    "projects.testing": "Testing",
    "projects.operating": "Operating",
    "projects.production": "Production",
    "projects.completed": "Completed",
    "projects.underReview": "Under Review",
    "projects.delayed": "Delayed",
    "projects.allProjects": "All Projects",
    "projects.applicationName": "Application Name",
    "projects.projectOwner": "Project Owner",
    "projects.alternativeOwner": "Alternative Owner",
    "projects.owningUnit": "Owning Unit",
    "projects.startDate": "Start Date",
    "projects.expectedCompletion": "Expected Completion",
    "projects.description": "Description",
    "projects.remarks": "Remarks",
    "projects.analysts": "Analysts",
    "projects.selectAnalysts": "Select Analysts",
    "projects.searchAnalysts": "Search for analysts...",
    "projects.selectedAnalysts": "Selected Analysts",
    "projects.removeAnalyst": "Remove Analyst",
    "projects.noAnalystsSelected": "No analysts selected",
    "projects.status": "Status",
    "projects.actions": "Actions",
    "projects.editProject": "Edit Project",
    "projects.deleteProject": "Delete Project",
    "projects.send": "Send for Review",
    "projects.addProject": "Add New Project",
    "projects.updateProject": "Update Project",
    "projects.viewDetails": "View Details",
    "projects.projectDetails": "Project Details",
    "projects.project": "Project",
    "projects.attachments": "Attachments",
    "projects.teamMembers": "Team Members",
    "projects.technologies": "Technologies",
    "projects.uploadFile": "Upload File",
    "projects.addDeveloper": "Add Developer",
    "projects.addTechnology": "Add Technology",
    "projects.manageTechnologies": "Manage Technologies",
    "projects.technologyCategories": "Technology Categories",
    "projects.fileName": "File Name",
    "projects.fileNamePlaceholder": "File name",
    "projects.fileNote": "Note",
    "projects.fileNotePlaceholder": "Note (optional)",
    "projects.selectDeveloper": "Select Developer",
    "projects.selectDeveloperPlaceholder": "Select developer",
    "projects.selectTechnology": "Select Technology",
    "projects.selectTechnologyPlaceholder": "Technology",
    "projects.technologyCategory": "Category",
    "projects.technologyCategoryPlaceholder": "Category",
    "projects.upload": "Upload",
    "projects.noFilesUploaded": "No files uploaded yet",
    "projects.noTeamMembersAssigned": "No team members assigned yet",
    "projects.noTechnologiesSelected": "No technologies selected yet",
    "projects.overview": "Overview",
    "projects.basicInformation": "Basic Information",
    "projects.attachedFiles": "Attached Files",
    "projects.currentTeamMembers": "Current Team Members",
    "projects.currentTechnologies": "Current Technologies",
    "projects.selectFile": "Select File",
    "projects.uploadFirstFile": "Upload your first file to get started",
    "projects.addFirstTeamMember": "Add your first team member",
    "projects.addFirstTechnology": "Add your first technology",
    "projects.downloadFile": "Download File",
    "projects.deleteFile": "Delete File",
    "projects.removeDeveloper": "Remove Developer",
    "projects.removeTechnology": "Remove Technology",
    "projects.technologyName": "Technology Name",
    "projects.technologyNamePlaceholder": "Enter technology name",
    "projects.customCategory": "Custom Category",
    "projects.customCategoryPlaceholder": "Enter custom category name",
    "projects.customCategoryDescription":
      "Or create a custom category instead of selecting above",
    "projects.technologyDescription": "Description",
    "projects.confirmDelete": "Confirm Delete",
    "projects.deleteConfirmMessage":
      "Are you sure you want to delete the project",
    "projects.actionCannotBeUndone": "This action cannot be undone.",
    "projects.noProjectsFound": "No projects found",
    "projects.noProjectsOnPage":
      "No projects on this page. Try a different page.",
    "projects.startFirstProject": "Start by creating your first project.",
    "projects.fillProjectDetails": "Fill in the project details below",
    "projects.updateProjectInfo": "Update project information",
    "projects.searchByName": "Search by name, military number, or username",
    "projects.noRemarks": "No remarks",

    // Project Validation Messages
    "projects.validation.applicationNameRequired":
      "Application name is required",
    "projects.validation.projectOwnerRequired": "Project owner is required",
    "projects.validation.owningUnitRequired": "Owning unit is required",
    "projects.validation.startDateRequired": "Start date is required",
    "projects.validation.expectedCompletionRequired":
      "Expected completion date is required",

    // Project Export Messages
    "projects.exportSuccess": "Projects exported successfully",
    "projects.exportError": "Failed to export projects",
    "projects.noDataToExport": "No projects available to export",
    "projects.sendSuccess": "Project sent for review successfully",
    "projects.sendError": "Failed to send project for review",

    // Project Requirements
    "requirements.title": "Project Requirements",
    "requirements.subtitle": "Manage project requirements and analysis",
    "requirements.assignedProjects": "Assigned Projects",
    "requirements.projectRequirements": "Project Requirements",
    "requirements.newRequirement": "New Requirement",
    "requirements.editRequirement": "Edit Requirement",
    "requirements.deleteRequirement": "Delete Requirement",
    "requirements.requirementName": "Requirement Name",
    "requirements.requirementDescription": "Description",
    "requirements.priority": "Priority",
    "requirements.type": "Requirement Type",
    "requirements.expectedCompletion": "Expected Completion Date",
    "requirements.attachments": "Attachments",
    "requirements.status": "Status",
    "requirements.saveAsDraft": "Save as Draft",
    "requirements.sendToDevelopment": "Send to Development",
    "requirements.startDevelopment": "Start Development",
    "requirements.cancel": "Cancel",
    "requirements.requirementNamePlaceholder": "e.g. PDF Invoice Generation",
    "requirements.requirementDescriptionPlaceholder":
      "Describe the requirement details...",
    "requirements.selectPriority": "Select Priority",
    "requirements.selectType": "Select Requirement Type",
    "requirements.selectExpectedDate": "Select Expected Completion Date",
    "requirements.uploadAttachment": "Upload Attachment",
    "requirements.removeAttachment": "Remove Attachment",
    "requirements.noRequirements": "No requirements found",
    "requirements.createFirstRequirement": "Create your first requirement",
    "requirements.noAssignedProjects": "No assigned projects",
    "requirements.checkBackLater": "Check back later for new assignments",
    "requirements.projectInfo": "Project Information",
    "requirements.requirementsCount": "Requirements",
    "requirements.completedRequirements": "Completed",
    "requirements.lastActivity": "Last Activity",
    "requirements.viewRequirements": "View Requirements",
    "requirements.managementForProject": "Requirements Management for",
    "requirements.backToProjects": "Back to Projects",
    "requirements.addRequirement": "Add Requirement",
    "requirements.filterByStatus": "Filter by Status",
    "requirements.filterByPriority": "Filter by Priority",
    "requirements.searchRequirements": "Search requirements...",
    "requirements.confirmDelete": "Confirm Delete",
    "requirements.deleteConfirmMessage":
      "Are you sure you want to delete this requirement?",
    "requirements.actionCannotBeUndone": "This action cannot be undone.",
    "requirements.sent": "Sent",
    "requirements.draft": "Draft",
    "requirements.pending": "Pending Review",
    "requirements.approved": "Approved",
    "requirements.inDevelopment": "In Development",
    "requirements.in_development": "In Development",
    "requirements.indevelopment": "In Development",
    "requirements.developmentRequirements": "Development Requirements",
    "requirements.developmentRequirementsSubtitle":
      "View all requirements currently in development across projects",
    "requirements.noDevelopmentRequirements": "No requirements in development",
    "requirements.noDevelopmentRequirementsDesc":
      "There are currently no requirements marked as in development.",
    "requirements.totalInDevelopment": "Total in Development",
    "keyrequirements.indevelopment": "In Development",
    "requirements.project": "Project",
    "requirements.completed": "Completed",
    "requirements.high": "High",
    "requirements.medium": "Medium",
    "requirements.low": "Low",
    "requirements.new": "New",
    "requirements.changeRequest": "Change Request",
    "requirements.allStatuses": "All Statuses",
    "requirements.allPriorities": "All Priorities",
    "requirements.createSuccess": "Requirement created successfully",
    "requirements.updateSuccess": "Requirement updated successfully",
    "requirements.deleteSuccess": "Requirement deleted successfully",
    "requirements.sendSuccess": "Requirement sent to development successfully",
    "requirements.createError": "Failed to create requirement",
    "requirements.updateError": "Failed to update requirement",
    "requirements.deleteError": "Failed to delete requirement",
    "requirements.sendError": "Failed to send requirement",
    "requirements.loadError": "Failed to load requirements",
    // Missing keys used by development-requirements page
    "requirements.description": "Description",
    "requirements.id": "ID",
    "requirements.created": "Created",
    "common.viewDetails": "View Details",
    // Task creation keys
    "tasks.createTask": "Create Task",
    "tasks.editTask": "Edit Task",
    "tasks.developer": "Developer",
    "tasks.qcMember": "QC Member",
    "tasks.selectDeveloper": "Search for developer...",
    "tasks.selectQC": "Search for QC member...",
    "requirements.validation.nameRequired": "Requirement name is required",
    "requirements.validation.descriptionRequired": "Description is required",
    "requirements.validation.priorityRequired": "Priority is required",
    "requirements.validation.typeRequired": "Requirement type is required",
    "requirements.validation.expectedDateRequired":
      "Expected completion date is required",
    "requirements.emptyState.title": "No Requirements Yet",
    "requirements.emptyState.description":
      "Start by adding your first requirement for this project",
    "requirements.emptyState.action": "Add First Requirement",

    // File Upload Keys
    "requirements.uploadFiles": "Click to upload files",
    "requirements.existingAttachments": "Existing Attachments",
    "requirements.newFiles": "New Files",

    // Task Plan
    "taskPlan.title": "Task Plan",
    "taskPlan.subtitle": "View all requirements in development status",
    "taskPlan.allRequirements": "All Requirements",
    "taskPlan.inDevelopment": "In Development",
    "taskPlan.filterByProject": "Filter by Project",
    "taskPlan.searchRequirements": "Search requirements...",
    "taskPlan.noRequirements": "No requirements found",
    "taskPlan.noRequirementsDesc": "No requirements match your current filters",
    "taskPlan.selectProject": "Select Project",
    "taskPlan.allProjects": "All Projects",
    "taskPlan.showingResults": "Showing {total} requirements",
    "taskPlan.project": "Project",
    "taskPlan.requirementName": "Requirement",
    "taskPlan.priority": "Priority",
    "taskPlan.status": "Status",
    "taskPlan.dueDate": "Due Date",
    "taskPlan.actions": "Actions",

    // Timeline Validation Messages
    "validation.nameRequired": "Name is required",
    "validation.nameMinLength": "Name must be at least 2 characters",
    "validation.startDateRequired": "Start date is required",
    "validation.endDateRequired": "End date is required",
    "validation.endDateAfterStart": "End date must be after start date",

    // User Management
    "users.title": "User Management",
    "users.subtitle": "Manage system users, roles, and permissions",
    "users.addUser": "Add New User",
    "users.editUser": "Edit User",
    "users.deleteUser": "Delete User",
    "users.userName": "Username",
    "users.fullName": "Full Name",
    "users.militaryNumber": "Military Number",
    "users.gradeName": "Grade",
    "users.roles": "Roles",
    "users.actions": "Actions",
    "users.isVisible": "Active",
    "users.status": "Status",
    "users.searchEmployees":
      "Search employees by name, military number, or username",
    "users.noEmployeesFound": "No employees found",
    "users.selectEmployee": "Select Employee",
    "users.employeeNotFound": "Employee not found",
    "users.assignRoles": "Assign Role",
    "users.assignActions": "Assign Actions",
    "users.assignAdditionalActions": "Assign Additional Actions",
    "users.permissionsSummary": "Permissions Summary",
    "users.confirmDelete": "Confirm Delete User",
    "users.deleteConfirmMessage": "Are you sure you want to delete this user?",
    "users.userStats": "User Statistics",
    "users.totalUsers": "Total Users",
    "users.activeUsers": "Active Users",
    "users.inactiveUsers": "Inactive Users",
    "users.usersByRole": "Users by Role",
    "users.accountStatus": "Account Status",
    "users.activeDescription": "User is active and can access the system",
    "users.inactiveDescription":
      "User is inactive and cannot access the system",

    // Department Management
    "departments.title": "Department Management",
    "departments.subtitle":
      "Manage organizational departments and their members",
    "departments.addDepartment": "Add New Department",
    "departments.editDepartment": "Edit Department",
    "departments.deleteDepartment": "Delete Department",
    "departments.viewMembers": "View Members",
    "departments.manageMembers": "Manage Members",
    "departments.name": "Department Name",
    "departments.nameAr": "Arabic Name",
    "departments.status": "Status",
    "departments.description": "Description",
    "departments.memberCount": "Members",
    "departments.createdAt": "Created Date",
    "departments.updatedAt": "Last Updated",
    "departments.actions": "Actions",
    "departments.active": "Active",
    "departments.inactive": "Inactive",
    "departments.searchDepartments": "Search departments...",
    "departments.noDepartmentsFound": "No departments found",
    "departments.confirmDelete": "Confirm Delete Department",
    "departments.deleteConfirmMessage":
      "Are you sure you want to delete this department?",
    "departments.deleteWarning":
      "All members will be removed from this department.",
    "departments.fillDepartmentDetails": "Fill in the department details below",
    "departments.updateDepartmentInfo": "Update department information",

    // Department Members
    "departments.members.title": "Department Members",
    "departments.members.addMember": "Add Member",
    "departments.members.editMember": "Edit Member",
    "departments.members.removeMember": "Remove Member",
    "departments.members.searchEmployee": "Search Employee",
    "departments.members.manualEntry": "Manual Entry",
    "departments.members.selectEmployee": "Select an employee",
    "departments.members.employeeNotFound":
      "Employee not found? You can add manually",
    "departments.members.userName": "Username",
    "departments.members.fullName": "Full Name",
    "departments.members.militaryNumber": "Military Number",
    "departments.members.gradeName": "Grade",
    "departments.members.role": "Role",
    "departments.members.joinedAt": "Joined Date",
    "departments.members.isActive": "Active",
    "departments.members.manager": "Manager",
    "departments.members.supervisor": "Supervisor",
    "departments.members.member": "Member",
    "departments.members.noMembersFound": "No members found in this department",
    "departments.members.confirmRemove": "Confirm Remove Member",
    "departments.members.removeConfirmMessage":
      "Are you sure you want to remove this member from the department?",
    "departments.members.searchPlaceholder":
      "Search by name, military number, or username",

    // Department Statistics
    "departments.stats.title": "Department Statistics",
    "departments.stats.totalDepartments": "Total Departments",
    "departments.stats.activeDepartments": "Active Departments",
    "departments.stats.inactiveDepartments": "Inactive Departments",
    "departments.stats.totalMembers": "Total Members",

    // Units Management
    "units.title": "Units Management",
    "units.subtitle": "Manage organizational units hierarchy",
    "units.selectUnit": "Select Unit",
    "units.searchUnits": "Search units...",
    "units.noUnits": "No units found",
    "units.noSearchResults": "No units found matching your search",
    "units.expandAll": "Expand All",
    "units.collapseAll": "Collapse All",
    "units.unitPath": "Unit Path",
    "units.selectedPath": "Selected Unit Path",
    "units.selected": "Selected",
    "units.level": "Level",
    "units.code": "Unit Code",
    "units.name": "Unit Name",
    "units.nameAr": "Arabic Name",
    "units.description": "Description",
    "units.parentUnit": "Parent Unit",
    "units.childUnits": "Child Units",
    "units.isActive": "Active",
    "units.inactive": "Inactive",

    // Roles
    "roles.title": "Role Management",
    "roles.name": "Role Name",
    "roles.description": "Description",
    "roles.active": "Active",
    "roles.order": "Order",
    "roles.permissions": "Permissions",
    "roles.assignActions": "Assign Actions",
    "roles.selectRole": "Select a Role",
    "roles.role": "Role",

    // Actions/Permissions
    "actions.title": "Action Management",
    "actions.name": "Action Name",
    "actions.category": "Category",
    "actions.description": "Description",
    "actions.userManagement": "User Management",
    "actions.projectManagement": "Project Management",
    "actions.roleManagement": "Role Management",
    "actions.systemAdmin": "System Administration",
    "actions.defaultActions": "default actions",
    "actions.defaultActionsForRole": "Default actions for role",
    "actions.defaultActionsNote":
      "These actions are automatically granted with this role and cannot be removed.",
    "actions.totalActions": "Total Actions",
    "actions.defaultFromRole": "Default from Role",
    "actions.additionalSelected": "Additional Selected",
    "actions.scrollToSeeMore": "Scroll to see more categories",
    "actions.totalAvailable": "total actions available",
    "actions.selected": "Selected",
    "actions.selectActions": "Select Actions",
    "actions.selectAdditionalActions": "Select Additional Actions",
    "actions.selectAdditionalActionsDescription":
      "Choose additional permissions beyond the role's default actions",
    "actions.searchActions": "Search actions...",
    "actions.allCategories": "All Categories",
    "actions.actionsSelected": "actions selected",
    "actions.availableActions": "available actions",
    "actions.clearAll": "Clear All",
    "actions.selectAll": "Select All",
    "actions.selectNone": "Select None",
    "actions.noActionsFound": "No actions found matching your criteria",
    "actions.noAdditionalActionsAvailable": "No additional actions available",
    "actions.confirmSelection": "Confirm Selection",
    "actions.additionalActionsSelected": "additional actions selected",
    "actions.noAdditionalActionsSelected": "No additional actions selected",

    // Permissions
    "permissions.create": "Create",
    "permissions.read": "Read",
    "permissions.update": "Update",
    "permissions.delete": "Delete",
    "permissions.admin": "Administrator",
    "permissions.denied": "Access Denied",
    "permissions.insufficient":
      "Insufficient permissions to perform this action",

    // Access Denied
    "access.denied.title": "Access Denied",
    "access.denied.message":
      "You don't have permission to access this application.",
    "access.denied.loading": "Loading...",

    // Project Status Options
    // Project Status/Phases
    "projectStatus.1": "Under Study",
    "projectStatus.2": "Under Development",
    "projectStatus.3": "Testing Environment",
    "projectStatus.4": "Operating Environment",
    "projectStatus.5": "Production Environment",

    // Timeline
    "timeline.title": "Timeline Management",
    "timeline.subtitle":
      "Manage project timelines, sprints, requirements, and tasks",
    "timeline.newTimeline": "New Timeline",
    "timeline.filters": "Filters",
    "timeline.refresh": "Refresh",
    "timeline.selectProjectTimeline": "Select Project & Timeline",
    "timeline.chooseProjectTimeline": "Choose a project and timeline",
    "timeline.loadingProjects": "Loading projects...",
    "timeline.noProjectsAvailable": "No projects available",
    "timeline.loadingTimelines": "Loading timelines...",
    "timeline.noTimelines": 'No timelines - Click "New Timeline" to create one',
    "timeline.sprints": "Sprints",
    "timeline.sprint": "Sprint",
    "timeline.requirements": "Requirements",
    "timeline.requirement": "Requirement",
    "timeline.tasks": "Tasks",
    "timeline.task": "Task",
    "timeline.subtasks": "Subtasks",
    "timeline.subtask": "Subtask",
    "timeline.assignedMembers": "Assigned Members",
    "timeline.searchPlaceholder": "Search timelines, sprints, requirements...",
    "timeline.noTimelinesFound": "No timelines found",
    "timeline.noTimelinesDescription":
      "This project doesn't have any timelines yet.",
    "timeline.noTimelinesGeneral":
      "Select a project and create your first timeline to get started.",
    "timeline.createTimeline": "Create Timeline",
    "timeline.selectTimeline": "Select a timeline",
    "timeline.selectTimelineDescription":
      "Choose a timeline from the dropdown above to view its details.",
    "timeline.ganttView": "Gantt View",
    "timeline.treeView": "Tree View",
    "timeline.details": "Details",
    "timeline.timelineFilters": "Timeline Filters",
    "timeline.clearAll": "Clear All",
    "timeline.applyFilters": "Apply Filters",
    "timeline.autoSelectingFirst": "Auto-selecting first timeline for project",
    "timeline.loading": "loading...",

    // Timeline Create Modal
    "timeline.createModal.title": "Create Timeline",
    "timeline.createModal.editTitle": "Edit Timeline",
    "timeline.createModal.name": "Timeline Name",
    "timeline.createModal.description": "Description",
    "timeline.createModal.startDate": "Start Date",
    "timeline.createModal.endDate": "End Date",
    "timeline.createModal.cancel": "Cancel",
    "timeline.createModal.save": "Save Timeline",
    "timeline.createModal.update": "Update Timeline",
    "timeline.createModal.nameRequired": "Timeline name is required",
    "timeline.createModal.startDateRequired": "Start date is required",
    "timeline.createModal.endDateRequired": "End date is required",
    "timeline.createModal.endDateMustBeAfter":
      "End date must be after start date",
    "timeline.createModal.projectIdRequired": "Project ID is required",

    // Timeline TreeView
    "timeline.treeView.addSprint": "Add Sprint",
    "timeline.treeView.addRequirement": "Add Requirement",
    "timeline.treeView.addTask": "Add Task",
    "timeline.treeView.addSubtask": "Add Subtask",
    "timeline.treeView.create": "Create",
    "timeline.treeView.edit": "Edit",
    "timeline.treeView.delete": "Delete",
    "timeline.treeView.editSprint": "Edit Sprint",
    "timeline.treeView.deleteSprint": "Delete Sprint",
    "timeline.treeView.editRequirement": "Edit Requirement",
    "timeline.treeView.deleteRequirement": "Delete Requirement",
    "timeline.treeView.editTask": "Edit Task",
    "timeline.treeView.deleteTask": "Delete Task",
    "timeline.treeView.moveTask": "Move Task",
    "timeline.treeView.editSubtask": "Edit Subtask",
    "timeline.treeView.deleteSubtask": "Delete Subtask",
    "timeline.treeView.confirmDelete": "Are you sure you want to delete this",
    "timeline.treeView.cancel": "Cancel",
    "timeline.treeView.saveChanges": "Save Changes",
    "timeline.treeView.editModalTitle": "Edit",
    "timeline.treeView.name": "Name",
    "timeline.treeView.description": "Description",
    "timeline.treeView.startDate": "Start Date",
    "timeline.treeView.endDate": "End Date",
    "timeline.treeView.department": "Department",
    "timeline.treeView.assignedTo": "Assigned To",
    "timeline.treeView.status": "Status",
    "timeline.treeView.priority": "Priority",
    "timeline.treeView.progress": "Progress",
    "timeline.treeView.notes": "Additional Notes",
    "timeline.treeView.sprintsLabel": "Sprints",
    "timeline.treeView.requirementsLabel": "Requirements",
    "timeline.treeView.tasksLabel": "Tasks",
    "timeline.treeView.subtasksLabel": "Subtasks",
    "timeline.treeView.timelineLabel": "Timeline",
    "timeline.treeView.progressColorLegend": "Progress Color Legend",
    "timeline.treeView.hierarchyColorLegend": "Hierarchy Color Legend",
    "timeline.treeView.progressCritical": "0-25% (Critical)",
    "timeline.treeView.progressBehind": "26-50% (Behind)",
    "timeline.treeView.progressOnTrack": "51-75% (On Track)",
    "timeline.treeView.progressExcellent": "76-100% (Excellent)",
    "timeline.treeView.loadingTimeline": "Loading timeline...",
    "timeline.treeView.searchPlaceholder":
      "Search sprints, requirements, tasks...",
    "timeline.treeView.filtered": "Filtered",

    // Timeline Move Task Modal
    "timeline.moveTask.title": "Move Task",
    "timeline.moveTask.subtitle":
      'Move "{taskName}" by the specified number of days',
    "timeline.moveTask.quickMoveOptions": "Quick Move Options",
    "timeline.moveTask.customMove": "Custom Move",
    "timeline.moveTask.movePlus1Day": "Move +1 Day",
    "timeline.moveTask.moveMinus1Day": "Move -1 Day",
    "timeline.moveTask.movePlus1Week": "Move +1 Week",
    "timeline.moveTask.moveMinus1Week": "Move -1 Week",
    "timeline.moveTask.enterDays": "Enter days (e.g. 5, -3)",
    "timeline.moveTask.daysDescription":
      "Positive numbers move forward, negative backward",
    "timeline.moveTask.move": "Move",
    "timeline.moveTask.cancel": "Cancel",
    "timeline.moveTask.successMessage":
      "Task moved successfully by {days} days",
    "timeline.moveTask.errorMessage": "Failed to move task",
    "timeline.moveTask.invalidDays": "Please enter a valid number of days",

    // Timeline Move Requirement Modal
    "timeline.moveRequirement.title": "Move Requirement",
    "timeline.moveRequirement.subtitle":
      "Move this requirement to another sprint",
    "timeline.moveRequirement.currentRequirement": "Current Requirement",
    "timeline.moveRequirement.currentSprint": "Current Sprint",
    "timeline.moveRequirement.selectTargetSprint": "Select Target Sprint",
    "timeline.moveRequirement.selectSprint": "Choose a sprint...",
    "timeline.moveRequirement.searchSprints": "Search sprints...",
    "timeline.moveRequirement.noSprintsAvailable": "No other sprints available",
    "timeline.moveRequirement.moveSummary": "Move Summary",
    "timeline.moveRequirement.movingRequirement": "Moving requirement",
    "timeline.moveRequirement.fromSprint": "From sprint",
    "timeline.moveRequirement.toSprint": "To sprint",
    "timeline.moveRequirement.moveButton": "Move Requirement",
    "timeline.moveRequirement.moving": "Moving...",
    "timeline.moveRequirement.success": "Success!",
    "timeline.moveRequirement.successMessage": "Requirement moved successfully",
    "timeline.treeView.moveRequirement": "Move Requirement",

    // Move Task Between Requirements translations
    "timeline.moveTaskToRequirement.title": "Move Task",
    "timeline.moveTaskToRequirement.subtitle":
      "Move this task to another requirement",
    "timeline.moveTaskToRequirement.currentTask": "Current Task",
    "timeline.moveTaskToRequirement.currentRequirement": "Current Requirement",
    "timeline.moveTaskToRequirement.selectTargetRequirement":
      "Select Target Requirement",
    "timeline.moveTaskToRequirement.selectRequirement":
      "Choose a requirement...",
    "timeline.moveTaskToRequirement.searchRequirements":
      "Search requirements...",
    "timeline.moveTaskToRequirement.noRequirementsAvailable":
      "No other requirements available",
    "timeline.moveTaskToRequirement.moveSummary": "Move Summary",
    "timeline.moveTaskToRequirement.movingTask": "Moving task",
    "timeline.moveTaskToRequirement.fromRequirement": "From requirement",
    "timeline.moveTaskToRequirement.toRequirement": "To requirement",
    "timeline.moveTaskToRequirement.moveButton": "Move Task",
    "timeline.moveTaskToRequirement.moving": "Moving...",
    "timeline.moveTaskToRequirement.success": "Success!",
    "timeline.moveTaskToRequirement.successMessage": "Task moved successfully",
    "timeline.treeView.moveTaskToRequirement": "Move Task",

    // Timeline TreeView Additional Keys
    "timeline.treeView.moveTaskToSprint": "Move Task to Sprint",
    "timeline.treeView.currentTask": "Current Task",
    "timeline.treeView.currentSprint": "Current Sprint",
    "timeline.treeView.selectTargetSprint": "Select Target Sprint",
    "timeline.treeView.selectSprint": "Choose a sprint...",

    "timeline.filters.search": "Search",
    "timeline.filters.searchPlaceholder":
      "Search timelines, sprints, requirements, or tasks...",
    "timeline.filters.activeFilters": "Active Filters",
    "timeline.filters.clearAll": "Clear All",
    "timeline.filters.dept": "Dept",
    "timeline.filters.member": "Member",
    "timeline.filters.status": "Status",
    "timeline.filters.priority": "Priority",
    "timeline.filters.departments": "Departments",
    "timeline.filters.assignedUsers": "Assigned Users",
    "timeline.filters.searchUsers": "Search users...",
    "timeline.filters.taskStatus": "Task Status",
    "timeline.filters.taskPriority": "Task Priority",
    "timeline.filters.unavailable": "Unavailable",
    "timeline.filters.notStarted": "Not Started",
    "timeline.filters.inProgress": "In Progress",
    "timeline.filters.completed": "Completed",
    "timeline.filters.onHold": "On Hold",
    "timeline.filters.cancelled": "Cancelled",
    "timeline.filters.low": "Low",
    "timeline.filters.medium": "Medium",
    "timeline.filters.high": "High",
    "timeline.filters.critical": "Critical",
    "timeline.create.title": "Create New Timeline",
    "timeline.create.subtitle":
      "Create a new timeline to organize your project phases",
    "timeline.create.timelineName": "Timeline Name",
    "timeline.create.timelineNamePlaceholder": "Enter timeline name",
    "timeline.create.description": "Description",
    "timeline.create.descriptionPlaceholder": "Describe this timeline (optional)",
    "timeline.create.startDate": "Start Date",
    "timeline.create.endDate": "End Date",
    "timeline.create.noProjectWarning":
      "Warning: No project selected. Please select a project first.",
    "timeline.create.cancel": "Cancel",
    "timeline.create.createTimeline": "Create Timeline",
    "timeline.create.nameRequired": "Timeline name is required",
    "timeline.create.startDateRequired": "Start date is required",
    "timeline.create.endDateRequired": "End date is required",
    "timeline.create.endDateAfterStart": "End date must be after start date",
    "timeline.create.projectRequired": "Project ID is required",
    "timeline.create.failedToCreate": "Failed to create timeline",
    "timeline.pageTitle": "Project Timeline",
    "timeline.pageDescription":
      "Manage project timelines, sprints, requirements, and tasks",

    // Timeline Details Panel
    "timeline.detailsPanel.noItemSelected": "No item selected",
    "timeline.detailsPanel.selectAnItem":
      "Select an item from the tree to view its details",
    "timeline.detailsPanel.overview": "Overview",
    "timeline.detailsPanel.description": "Description",
    "timeline.detailsPanel.startDate": "Start Date",
    "timeline.detailsPanel.endDate": "End Date",
    "timeline.detailsPanel.duration": "Duration",
    "timeline.detailsPanel.days": "days",
    "timeline.detailsPanel.status": "Status",
    "timeline.detailsPanel.priority": "Priority",
    "timeline.detailsPanel.progress": "Progress",
    "timeline.detailsPanel.department": "Department",
    "timeline.detailsPanel.selectDepartment": "Select department",
    "timeline.detailsPanel.assignedTo": "Assigned To",
    "timeline.detailsPanel.edit": "Edit",
    "timeline.detailsPanel.cancel": "Cancel",
    "timeline.detailsPanel.saveChanges": "Save Changes",
    "timeline.detailsPanel.projectId": "Project ID",
    "timeline.detailsPanel.structure": "Structure",
    "timeline.detailsPanel.tasks": "Tasks",
    "timeline.detailsPanel.subtasks": "Subtasks",
    "timeline.detailsPanel.statusAndPriority": "Status & Priority",
    "timeline.detailsPanel.additionalNotes": "Additional notes",
    "timeline.detailsPanel.estimated": "Estimated",
    "timeline.detailsPanel.actual": "Actual",
    "timeline.detailsPanel.selectStatus": "Select status",
    "timeline.detailsPanel.selectPriority": "Select priority",
    "timeline.chooseTask": "Choose Task",
    "timeline.selectPredecessors": "Select Predecessors",
    "timeline.selectPredecessorsPlaceholder": "Choose a predecessor task...",
    "timeline.searchTask": "Search for a task",

    ///Gantt view
    "timeline.taskName": "Task Name",
    "timeline.startDate": "Start Date",
    "timeline.duration": "Duration",
    "timelane.back": "Back",
    "timeline.month": "Mohth",
    "timeline.day": "Day",
    "timeline.week": "Week",
    "timeline.year": "Year",
    "timeline.normalSize": "Normal Size",
    "timeline.largeSize": "Large Size",
    "timeline.controlCellHeight": "Control Size",
    "timeline.gantt.description": "Description",
    "timeline.gantt.period": "Duration",
    "timeline.gantt.save": "Save",
    "timeline.gantt.cancel": "Cancel",
    "timeline.gantt.delete": "Delete",
    "timeline.gantt.progress": "Progess",
    "timeline.gantt.editTask": "Update Task",
    // Members Tasks Dashboard
    membersTasksDashboard: "Members Tasks Dashboard",
    tasksOverview: "Tasks Overview",

    // Filters
    filterByAssignees: "Filter by Assignees",
    filterByDepartment: "Filter by Department",
    filterByStatus: "Filter by Status",
    filterByPriority: "Filter by Priority",
    filterByDateRange: "Filter by Date Range",
    showOverdueOnly: "Show Overdue Only",
    anyAssigneeMode: "Tasks with ANY selected assignee",
    allAssigneesMode: "Tasks with ALL selected assignees",
    clearAllFilters: "Clear All Filters",
    activeFilters: "Active Filters",

    // Task Card
    primaryAssignee: "Primary Assignee",
    otherAssignees: "Other Assignees",
    moreAssignees: "more assignees",
    taskProgress: "Progress",
    timeSpent: "Time Spent",
    estimatedTime: "Estimated Time",
    taskTags: "Tags",
    overdueTask: "Overdue",
    taskDetails: "Task Details",

    // Export
    exportTasks: "Export Tasks",
    exportAsCSV: "Export as CSV",
    exportAsPDF: "Export as PDF",
    exportAsExcel: "Export as Excel",

    // States
    noTasksFound: "No tasks found",
    adjustFiltersMessage: "Try adjusting your filters to see more results",
    loadingTasks: "Loading tasks...",
    errorLoadingTasks: "Error loading tasks",
    selectDepartment: "Select Department",
    selectStatus: "Select Status",
    selectPriority: "Select Priority",
  },
  ar: {
    // Navbar
    "nav.dashboard": "لوحة التحكم",
    "nav.projects": "المشاريع",
    "nav.requirements": "قيد التحليل",
    "nav.developmentRequirements": "قيد التطوير",
    "nav.taskPlan": "خطة المهام",
    "nav.users": "المستخدمين",
    "nav.timeline": "المخطط الزمني",
    "nav.tasks": "المهام",
    "nav.departments": "الأقسام",
    "nav.reports": "التقارير",
    "nav.newProject": "مشروع جديد",
    "nav.notifications": "الإشعارات",
    "nav.notificationsTitle": "الإشعارات",
    "nav.search": "البحث في المشاريع والمهام والأشخاص...",
    "nav.searchModal": "البحث",
    "nav.searchPlaceholder": "البحث في المشاريع والمهام وأعضاء الفريق...",
    "nav.searchResults": "نتائج البحث عن",
    "nav.searchPrompt":
      "ابدأ الكتابة للبحث في المشاريع والمهام وأعضاء الفريق...",
    "nav.noNotifications": "لا توجد إشعارات",
    "nav.markAllRead": "تحديد الكل كمقروء",

    // Urgent Notifications
    "notifications.urgent": "عاجل",
    "notifications.minimize": "تصغير",
    "notifications.markAsRead": "تعليم كمقروء",
    "dashboard.urgentNotifications": "إشعارات عاجلة",
    "dashboard.updates": "التحديثات",
    "dashboard.projectPipeline": "خط سير المشروع",
    "dashboard.requirementOverview": "نظرة عامة على المتطلبات",
    "requirements.ongoing": "متطلبات قيد التنفيذ",
    "requirements.active": "المتطلبات النشطة",
    "requirements.pendingApprovals": "موافقات معلقة",

    // Project Pipeline
    "pipeline.planning": "التخطيط",
    "pipeline.inProgress": "قيد التنفيذ",
    "pipeline.completed": "مكتمل",
    "pipeline.noProjects": "لا توجد مشاريع في هذه المرحلة",

    // Common
    "common.owner": "المالك",
    "common.lastActivity": "آخر نشاط",
    "common.tryAgainLater": "يرجى المحاولة مرة أخرى لاحقاً",
    "common.projectManagement": "إدارة المشاريع",
    "pipeline.initiatePlanning": "بدء التخطيط",
    "pipeline.reviewRequirements": "مراجعة المتطلبات",
    "pipeline.resourceAllocation": "تخصيص الموارد",
    "pipeline.assignTeamMembers": "تعيين أعضاء الفريق",
    "pipeline.activeDevelopment": "التطوير النشط",
    "pipeline.codingPhase": "مرحلة البرمجة",
    "pipeline.testing": "الاختبار",
    "pipeline.qualityAssurance": "ضمان الجودة",
    "pipeline.deployment": "النشر",
    "pipeline.liveProduction": "الإنتاج المباشر",
    "pipeline.maintenance": "الصيانة",
    "pipeline.ongoingSupport": "الدعم المستمر",

    // Calendar
    "calendar.title": "التقويم",
  "calendar.previousMonth": "الشهر السابق",
  "calendar.nextMonth": "الشهر التالي", 
  "calendar.month": "شهر",
    "calendar.week": "أسبوع",
    "calendar.day": "يوم",
    "calendar.today": "اليوم",
    "calendar.addEvent": "إضافة حدث",
    "calendar.overview": "نظرة عامة",
    "calendar.upcoming": "قادم",
    "calendar.overdue": "متأخر",
    "calendar.completedWeek": "مكتمل هذا الأسبوع",
    "calendar.critical": "المواعيد النهائية الحرجة",
    "calendar.upcomingEvents": "الأحداث القادمة",
    "calendar.overdueEvents": "الأحداث المتأخرة",
    "calendar.noEvents": "لم يتم العثور على أحداث",
    "calendar.noUpcoming": "لا توجد أحداث قادمة",
    "calendar.description": "الوصف",
    "calendar.startDate": "تاريخ البداية",
    "calendar.endDate": "تاريخ النهاية",
    "calendar.startDateTime": "تاريخ ووقت البداية",
    "calendar.endDateTime": "تاريخ ووقت النهاية",
    "calendar.startTime": "وقت البداية",
    "calendar.endTime": "وقت النهاية",
    "calendar.status": "الحالة",
    "calendar.priority": "الأولوية",
    "calendar.location": "الموقع",
    "calendar.editEvent": "تعديل الحدث",
    "calendar.sun": "أحد",
    "calendar.mon": "اثنين",
    "calendar.tue": "ثلاثاء",
    "calendar.wed": "أربعاء",
    "calendar.thu": "خميس",
    "calendar.fri": "جمعة",
    "calendar.sat": "سبت",
    "calendar.type": "النوع",
    "calendar.type.project": "مشروع",
    "calendar.type.requirement": "متطلب",
    "calendar.type.meeting": "اجتماع",
    "calendar.type.deadline": "موعد نهائي",
    "calendar.type.milestone": "معلم",
    "calendar.status.upcoming": "قادم",
    "calendar.status.in-progress": "قيد التنفيذ",
    "calendar.status.completed": "مكتمل",
    "calendar.status.overdue": "متأخر",
    "calendar.priority.low": "منخفض",
    "calendar.priority.medium": "متوسط",
    "calendar.priority.high": "عالي",
    "calendar.priority.critical": "حرج",
    "calendar.eventTitle": "العنوان",
    "calendar.titlePlaceholder": "أدخل عنوان الحدث",
    "calendar.descriptionPlaceholder": "أدخل وصف الحدث",
    "calendar.locationPlaceholder": "أدخل الموقع",
    "calendar.allDay": "طوال اليوم",

    // Calendar Filters
    "calendar.search": "البحث",
    "calendar.searchPlaceholder": "البحث في الأحداث...",
    "calendar.allTypes": "جميع الأنواع",
    "calendar.allPriorities": "جميع الأولويات",
    "calendar.clearFilters": "مسح المرشحات",
    "calendar.eventTypes.meeting": "اجتماع",
    "calendar.eventTypes.task": "مهمة",
    "calendar.eventTypes.deadline": "موعد نهائي",
    "calendar.eventTypes.project": "مشروع",
    "calendar.eventTypes.requirement": "متطلب",
    "calendar.priorities.low": "منخفض",
    "calendar.priorities.medium": "متوسط",
    "calendar.priorities.high": "عالي",
    "calendar.priorities.urgent": "عاجل",

    // Calendar Color Legend
    "calendar.colorLegend": "مفتاح الألوان",
    "calendar.visualEffects": "التأثيرات البصرية",
    "calendar.criticalShadow": "أولوية حرجة",
    "calendar.priorityBorder": "حدود الأولوية",

    // Calendar Validation Messages
    "calendar.validation.titleRequired": "عنوان الحدث مطلوب",
    "calendar.validation.startDateRequired": "تاريخ البداية مطلوب",
    "calendar.validation.startTimeRequired": "وقت البداية مطلوب",
    "calendar.validation.endDateBeforeStart":
      "لا يمكن أن يكون تاريخ النهاية قبل تاريخ البداية",
    "calendar.validation.endTimeBeforeStart":
      "يجب أن يكون وقت النهاية بعد وقت البداية لأحداث نفس اليوم",
    "calendar.validation.saveFailed":
      "فشل في حفظ الحدث. يرجى المحاولة مرة أخرى.",

    // Common Date References
    "common.today": "اليوم",
    "common.yesterday": "أمس",

    // Global Search Arabic
    "search.title": "البحث الشامل",
    "search.placeholder":
      "البحث في المشاريع والمستخدمين والجداول الزمنية والمهام...",
    "search.filters": "المرشحات",
    "search.clearFilters": "مسح المرشحات",
    "search.type": "النوع",
    "search.status": "الحالة",
    "search.department": "القسم",
    "search.selectType": "اختر الأنواع",
    "search.selectStatus": "اختر الحالة",
    "search.selectDepartment": "اختر الأقسام",
    "search.noResults": "لم يتم العثور على نتائج",
    "search.tryDifferent": "جرب مصطلح بحث مختلف أو اضبط المرشحات",
    "search.recent": "عمليات البحث الأخيرة",
    "search.clear": "مسح",
    "search.suggestions": "اقتراحات",
    "search.startTyping": "ابدأ الكتابة للبحث",
    "search.searchDescription":
      "البحث في المشاريع والمستخدمين والجداول الزمنية والمهام والمزيد",
    "search.resultsCount": 'تم العثور على {count} نتيجة لـ "{query}"',

    // User Menu
    "user.account": "الحساب",
    "user.workspace": "مساحة العمل",
    "user.profile": "الملف الشخصي",
    "user.settings": "الإعدادات",
    "user.departmentManagement": "إدارة الأقسام",
    "user.billing": "الفواتير",
    "user.logout": "تسجيل الخروج",
    "user.profileDesc": "عرض وتحرير ملفك الشخصي",
    "user.settingsDesc": "تفضيلات الحساب",
    "user.departmentsDesc": "إدارة أعضاء الأقسام",
    "user.billingDesc": "عرض معلومات الفواتير",
    "user.logoutDesc": "تسجيل الخروج من حسابك",
    "user.administration": "الإدارة",
    "user.userManagement": "إدارة المستخدمين",
    "user.userManagementDesc": "إدارة المستخدمين والصلاحيات",
    "user.systemSettings": "إعدادات النظام",
    "user.systemSettingsDesc": "تكوين إعدادات النظام",
    "user.loading": "جاري تحميل بيانات المستخدم...",

    // Dashboard
    "dashboard.title": "لوحة تحكم إدارة المشاريع",
    "dashboard.subtitle": "تتبع وإدارة مشاريعك بكفاءة",
    "dashboard.projectsUnderReview": "المشاريع قيد المراجعة",
    "dashboard.requiredAttention": "تتطلب انتباه أربعة موظفين",
    "dashboard.overdueTasks": "المهام المتأخرة",
    "dashboard.dueDatesPassedAction": "تجاوزت تواريخ الاستحقاق، إجراء مطلوب",
    "dashboard.changeBehindSchedule": "التغيير متأخر عن المخطط",
    "dashboard.viewCurrentSchedule": "عرض المخطط الزمني الحالي",
    "dashboard.underReview": "قيد المراجعة",
    "dashboard.analysisInProgress": "التحليل قيد التقدم",
    "dashboard.awaitingDev": "في انتظار التطوير",
    "dashboard.teamWorkload": "عبء العمل للفريق",
    "dashboard.teamWorkloadPerformance": "عبء العمل والأداء للفريق",
    "dashboard.viewAllProjects": "عرض جميع المشاريع",
    "dashboard.teamName": "اسم الفريق",
    "dashboard.progressMapped": "التقدم المخطط",
    "dashboard.progressCompleted": "التقدم المكتمل | أسبوعياً |",
    "dashboard.avgTaskThroughput": "متوسط إنجاز المهام | لكل |",
    "dashboard.nexus": "الرابط",
    "dashboard.managerTeams": "فرق المديرين",
    "dashboard.noManagerTeamsData": "لا توجد بيانات فرق مديرين متاحة",
    "dashboard.requirementsOverview": "نظرة عامة على المتطلبات",
    "dashboard.newRequirements": "المتطلبات الجديدة",
    "dashboard.changeRequests": "طلبات التغيير",
    "dashboard.totalActiveRequirements": "إجمالي المتطلبات النشطة",
    "dashboard.pendingApproval": "في انتظار الموافقة",
    "dashboard.viewAllRequirementLog": "عرض جميع سجلات المتطلبات",
    "dashboard.newProject": "مشروع جديد",
    "dashboard.activeProjects": "المشاريع النشطة",
    "dashboard.totalTasks": "إجمالي المهام",
    "dashboard.inProgress": "قيد التنفيذ",
    "dashboard.overdue": "متأخرة",
    "dashboard.importData": "استيراد البيانات",
    "dashboard.viewDetails": "عرض التفاصيل",
    "dashboard.recentTasks": "المهام الحديثة",
    "dashboard.tasks": "المهام",
    "dashboard.due": "الاستحقاق",
    "dashboard.progress": "التقدم",
    "dashboard.teamMembers": "أعضاء الفريق",
    "dashboard.task": "المهمة",
    "dashboard.assignee": "المُعين",
    "dashboard.status": "الحالة",
    "dashboard.priority": "الأولوية",
    "dashboard.dueDate": "تاريخ الاستحقاق",
    "dashboard.assignedTo": "مُعين إلى",

    // Team Workload
    "team.member": "عضو الفريق",
    "team.department": "القسم",
    "team.total": "الإجمالي",
    "team.inProgress": "قيد التنفيذ",
    "team.completed": "مكتمل",
    "team.performance": "الأداء",
    "team.busy": "مشغول",
    "team.available": "متاح",
    "team.busyUntilToday": "مشغول حتى نهاية اليوم",
    "team.busyUntilTomorrow": "مشغول حتى الغد",
    "team.busyUntilDays": "مشغول لـ {days} أيام أخرى",
    "team.busyUntilDate": "مشغول حتى {date}",
    "team.search": "البحث",
    "team.searchPlaceholder": "البحث في أعضاء الفريق...",
    "team.allDepartments": "جميع الأقسام",
    "team.busyStatus": "الحالة",
    "team.allStatuses": "جميع الحالات",
    "team.performanceRange": "الأداء",
    "team.allPerformance": "جميع مستويات الأداء",
    "team.excellent": "ممتاز",
    "team.good": "جيد",
    "team.average": "متوسط",
    "team.poor": "ضعيف",
    "team.filtered": "مُرشح",
    "team.clearFilters": "مسح المرشحات",
    "team.noFilterResults": "لا يوجد أعضاء فريق تطابق المرشحات الحالية",
    "team.members": "أعضاء",

    // Project Status
    "status.active": "نشط",
    "status.completed": "مكتمل",
    "status.onHold": "معلق",
    "status.todo": "للقيام",
    "status.inProgress": "قيد التنفيذ",

    // Priority
    "priority.high": "عالية",
    "priority.medium": "متوسطة",
    "priority.low": "منخفضة",

    // Common
    "common.total": "المجموع",
    "common.retry": "إعادة المحاولة",
    "common.actions": "الإجراءات",
    "common.due": "تاريخ الاستحقاق",
    "common.tasks": "مهام",
    "common.progress": "التقدم",
    "common.close": "إغلاق",
    "common.edit": "تحرير",
    "common.view": "عرض",
    "common.save": "حفظ",
    "common.refresh": "تحديث",
    "common.editProject": "تحرير المشروع",
    "common.cancel": "إلغاء",
    "common.select": "اختيار",
    "common.clear": "مسح",
    "common.search": "بحث",
    "common.delete": "حذف",
    "common.remove": "إزالة",
    "common.add": "إضافة",
    "common.create": "إنشاء",
    "common.update": "تحديث",
    "common.error": "خطأ",
    "common.all": "الكل",
    "common.inactive": "غير نشط",
    "common.show": "عرض",
    "common.loading": "جاري التحميل...",
    "common.searching": "جاري البحث",
    "common.pleaseWait": "يرجى الانتظار...",
    "common.noDataFound": "لا توجد بيانات",
    "common.unexpectedError": "حدث خطأ غير متوقع",

    // Table
    "table.noData": "لا توجد بيانات متاحة",

    // Pagination
    "pagination.showing": "عرض",
    "pagination.to": "إلى",
    "pagination.of": "من",
    "pagination.items": "عنصر",
    "pagination.page": "صفحة",
    "pagination.perPage": "لكل صفحة",
    "pagination.goTo": "الذهاب إلى الصفحة",
    "pagination.previous": "السابق",
    "pagination.next": "التالي",
    "pagination.first": "الأولى",
    "pagination.last": "الأخيرة",
    "pagination.loading": "جاري تحميل الصفحة...",
    "pagination.loadingPage": "جاري تحميل الصفحة {page}...",

    // Projects
    "projects.title": "إدارة المشاريع",
    "projects.subtitle": "إدارة جميع تطبيقات ومشاريع المؤسسة",
    "projects.newProject": "مشروع جديد",
    "projects.importProjects": "استيراد المشاريع",
    "projects.exportData": "تصدير البيانات",
    "projects.totalProjects": "إجمالي المشاريع",
    "projects.underStudy": "قيد الدراسة",
    "projects.underDevelopment": "قيد التطوير",
    "projects.testing": "بيئة الفحص",
    "projects.operating": "بيئة التشغيل",
    "projects.production": "بيئة الانتاج",
    "projects.completed": "مكتمل",
    "projects.underReview": "قيد المراجعة",
    "projects.delayed": "مؤجل",
    "projects.allProjects": "جميع المشاريع",
    "projects.applicationName": "اسم المشروع",
    "projects.projectOwner": "مدير المشروع",
    "projects.alternativeOwner": "مدير المشروع البديل",
    "projects.owningUnit": "الوحدة المالكة",
    "projects.startDate": "تاريخ البداية",
    "projects.expectedCompletion": "تاريخ الإنجاز المتوقع",
    "projects.description": "الوصف",
    "projects.remarks": "ملاحظات",
    "projects.analysts": "المحللين",
    "projects.selectAnalysts": "اختيار المحللين",
    "projects.searchAnalysts": "البحث عن محللين...",
    "projects.selectedAnalysts": "المحللين المختارين",
    "projects.removeAnalyst": "إزالة المحلل",
    "projects.noAnalystsSelected": "لم يتم اختيار محللين",
    "projects.status": "الحالة",
    "projects.actions": "الإجراءات",
    "projects.editProject": "تحرير المشروع",
    "projects.deleteProject": "حذف المشروع",
    "projects.send": "إرسال للمراجعة",
    "projects.addProject": "إضافة مشروع جديد",
    "projects.updateProject": "تحديث المشروع",
    "projects.viewDetails": "عرض التفاصيل",
    "projects.projectDetails": "تفاصيل المشروع",
    "projects.project": "مشروع",
    "projects.attachments": "المرفقات",
    "projects.teamMembers": "أعضاء الفريق",
    "projects.technologies": "التقنيات",
    "projects.uploadFile": "رفع ملف",
    "projects.addDeveloper": "إضافة مطور",
    "projects.addTechnology": "إضافة تقنية",
    "projects.manageTechnologies": "إدارة التقنيات",
    "projects.technologyCategories": "فئات التقنيات",
    "projects.fileName": "اسم الملف",
    "projects.fileNamePlaceholder": "اسم الملف",
    "projects.fileNote": "ملاحظة",
    "projects.fileNotePlaceholder": "ملاحظة (اختياري)",
    "projects.selectDeveloper": "اختر مطور",
    "projects.selectDeveloperPlaceholder": "اختر مطور",
    "projects.selectTechnology": "اختر تقنية",
    "projects.selectTechnologyPlaceholder": "التقنية",
    "projects.technologyCategory": "الفئة",
    "projects.technologyCategoryPlaceholder": "الفئة",
    "projects.upload": "رفع",
    "projects.noFilesUploaded": "لم يتم رفع أي ملفات بعد",
    "projects.noTeamMembersAssigned": "لم يتم تعيين أعضاء فريق بعد",
    "projects.noTechnologiesSelected": "لم يتم اختيار أي تقنيات بعد",
    "projects.overview": "نظرة عامة",
    "projects.basicInformation": "المعلومات الأساسية",
    "projects.attachedFiles": "الملفات المرفقة",
    "projects.currentTeamMembers": "أعضاء الفريق الحاليين",
    "projects.currentTechnologies": "التقنيات الحالية",
    "projects.selectFile": "اختر ملف",
    "projects.uploadFirstFile": "ارفع أول ملف للبدء",
    "projects.addFirstTeamMember": "أضف أول عضو فريق",
    "projects.addFirstTechnology": "أضف أول تقنية",
    "projects.downloadFile": "تحميل الملف",
    "projects.deleteFile": "حذف الملف",
    "projects.removeDeveloper": "إزالة المطور",
    "projects.removeTechnology": "إزالة التقنية",
    "projects.technologyName": "اسم التقنية",
    "projects.technologyNamePlaceholder": "أدخل اسم التقنية",
    "projects.customCategory": "فئة مخصصة",
    "projects.customCategoryPlaceholder": "أدخل اسم فئة مخصصة",
    "projects.customCategoryDescription":
      "أو أنشئ فئة مخصصة بدلاً من الاختيار من الأعلى",
    "projects.technologyDescription": "الوصف",
    "projects.confirmDelete": "تأكيد الحذف",
    "projects.deleteConfirmMessage": "هل أنت متأكد من رغبتك في حذف المشروع",
    "projects.actionCannotBeUndone": "لا يمكن التراجع عن هذا الإجراء.",
    "projects.noProjectsFound": "لم يتم العثور على مشاريع",
    "projects.noProjectsOnPage": "لا توجد مشاريع في هذه الصفحة. جرب صفحة أخرى.",
    "projects.startFirstProject": "ابدأ بإنشاء مشروعك الأول.",
    "projects.fillProjectDetails": "املأ تفاصيل المشروع أدناه",
    "projects.updateProjectInfo": "تحديث معلومات المشروع",
    "projects.searchByName": "البحث بالاسم أو الرقم العسكري أو اسم المستخدم",
    "projects.noRemarks": "لا توجد ملاحظات",

    // Project Validation Messages
    "projects.validation.applicationNameRequired": "اسم المشروع مطلوب",
    "projects.validation.projectOwnerRequired": "مدير المشروع مطلوب",
    "projects.validation.owningUnitRequired": "الوحدة المالكة مطلوبة",
    "projects.validation.startDateRequired": "تاريخ البداية مطلوب",
    "projects.validation.expectedCompletionRequired":
      "تاريخ الإنجاز المتوقع مطلوب",

    // Project Export Messages
    "projects.exportSuccess": "تم تصدير المشاريع بنجاح",
    "projects.exportError": "فشل في تصدير المشاريع",
    "projects.noDataToExport": "لا توجد مشاريع متاحة للتصدير",
    "projects.sendSuccess": "تم إرسال المشروع للمراجعة بنجاح",
    "projects.sendError": "فشل في إرسال المشروع للمراجعة",

    // Project Requirements
    "requirements.title": "متطلبات المشروع",
    "requirements.subtitle": "إدارة متطلبات المشروع والتحليل",
    "requirements.assignedProjects": "المشاريع المكلفة",
    "requirements.projectRequirements": "متطلبات المشروع",
    "requirements.newRequirement": "متطلب جديد",
    "requirements.editRequirement": "تحرير المتطلب",
    "requirements.deleteRequirement": "حذف المتطلب",
    "requirements.requirementName": "اسم المتطلب",
    "requirements.requirementDescription": "الوصف",
    "requirements.priority": "الأولوية",
    "requirements.type": "نوع المتطلب",
    "requirements.expectedCompletion": "تاريخ الإنجاز المتوقع",
    "requirements.attachments": "المرفقات",
    "requirements.status": "الحالة",
    "requirements.saveAsDraft": "حفظ كمسودة",
    "requirements.sendToDevelopment": "إرسال لمدير التطوير",
    "requirements.startDevelopment": "بدء التطوير",
    "requirements.cancel": "إلغاء",
    "requirements.requirementNamePlaceholder": "مثال: إصدار فاتورة PDF",
    "requirements.requirementDescriptionPlaceholder": "اكتب تفاصيل المتطلب...",
    "requirements.selectPriority": "اختر الأولوية",
    "requirements.selectType": "اختر نوع المتطلب",
    "requirements.selectExpectedDate": "اختر تاريخ الإنجاز المتوقع",
    "requirements.uploadAttachment": "رفع مرفق",
    "requirements.removeAttachment": "إزالة المرفق",
    "requirements.noRequirements": "لا توجد متطلبات",
    "requirements.createFirstRequirement": "أنشئ أول متطلب",
    "requirements.noAssignedProjects": "لا توجد مشاريع مكلفة",
    "requirements.checkBackLater": "تحقق لاحقاً من المهام الجديدة",
    "requirements.projectInfo": "معلومات المشروع",
    "requirements.requirementsCount": "المتطلبات",
    "requirements.completedRequirements": "المكتملة",
    "requirements.lastActivity": "آخر نشاط",
    "requirements.viewRequirements": "عرض المتطلبات",
    "requirements.managementForProject": "إدارة المتطلبات لمشروع",
    "requirements.backToProjects": "العودة للمشاريع",
    "requirements.addRequirement": "إضافة متطلب",
    "requirements.filterByStatus": "ترشيح حسب الحالة",
    "requirements.filterByPriority": "ترشيح حسب الأولوية",
    "requirements.searchRequirements": "البحث عن متطلبات...",
    "requirements.confirmDelete": "تأكيد الحذف",
    "requirements.deleteConfirmMessage": "هل أنت متأكد من حذف هذا المتطلب؟",
    "requirements.actionCannotBeUndone": "لا يمكن التراجع عن هذا الإجراء.",
    "requirements.sent": "مرسل",
    "requirements.draft": "مسودة",
    "requirements.pending": "قيد المراجعة",
    "requirements.approved": "موافق عليه",
    "requirements.inDevelopment": "قيد التطوير",
    "requirements.in_development": "قيد التطوير",
    "requirements.indevelopment": "قيد التطوير",
    "requirements.developmentRequirements": "متطلبات التطوير",
    "requirements.developmentRequirementsSubtitle":
      "عرض جميع المتطلبات التي هي قيد التطوير عبر المشاريع",
    "requirements.noDevelopmentRequirements": "لا توجد متطلبات قيد التطوير",
    "requirements.noDevelopmentRequirementsDesc":
      "لا توجد حالياً متطلبات موسومة بأنها قيد التطوير.",
    "requirements.totalInDevelopment": "إجمالي المتطلبات قيد التطوير",
    "keyrequirements.indevelopment": "قيد التطوير",
    "requirements.project": "المشروع",
    "requirements.completed": "مكتمل",
    "requirements.high": "عالية",
    "requirements.medium": "متوسطة",
    "requirements.low": "منخفضة",
    "requirements.new": "جديد",
    "requirements.changeRequest": "طلب تغيير",
    "requirements.allStatuses": "جميع الحالات",
    "requirements.allPriorities": "جميع الأولويات",
    "requirements.createSuccess": "تم إنشاء المتطلب بنجاح",
    "requirements.updateSuccess": "تم تحديث المتطلب بنجاح",
    "requirements.deleteSuccess": "تم حذف المتطلب بنجاح",
    "requirements.sendSuccess": "تم إرسال المتطلب للتطوير بنجاح",
    "requirements.createError": "فشل في إنشاء المتطلب",
    "requirements.updateError": "فشل في تحديث المتطلب",
    "requirements.deleteError": "فشل في حذف المتطلب",
    "requirements.sendError": "فشل في إرسال المتطلب",
    "requirements.loadError": "فشل في تحميل المتطلبات",
    // Missing keys used by development-requirements page (Arabic)
    "requirements.description": "الوصف",
    "requirements.id": "المعرّف",
    "requirements.created": "تاريخ الإنشاء",
    "common.viewDetails": "عرض التفاصيل",
    // Task creation keys (Arabic)
    "tasks.createTask": "إنشاء مهمة",
    "tasks.editTask": "تحرير المهمة",
    "tasks.developer": "المطور",
    "tasks.qcMember": "مسؤول ضمان الجودة",
    "tasks.selectDeveloper": "البحث عن مطور...",
    "tasks.selectQC": "البحث عن مسؤول ضمان الجودة...",
    "requirements.validation.nameRequired": "اسم المتطلب مطلوب",
    "requirements.validation.descriptionRequired": "الوصف مطلوب",
    "requirements.validation.priorityRequired": "الأولوية مطلوبة",
    "requirements.validation.typeRequired": "نوع المتطلب مطلوب",
    "requirements.validation.expectedDateRequired":
      "تاريخ الإنجاز المتوقع مطلوب",
    "requirements.emptyState.title": "لا توجد متطلبات بعد",
    "requirements.emptyState.description": "ابدأ بإضافة أول متطلب لهذا المشروع",
    "requirements.emptyState.action": "إضافة أول متطلب",

    // File Upload Keys (Arabic)
    "requirements.uploadFiles": "انقر لرفع الملفات",
    "requirements.existingAttachments": "المرفقات الموجودة",
    "requirements.newFiles": "الملفات الجديدة",

    // Task Plan
    "taskPlan.title": "خطة المهام",
    "taskPlan.subtitle": "عرض جميع المتطلبات في حالة التطوير",
    "taskPlan.allRequirements": "جميع المتطلبات",
    "taskPlan.inDevelopment": "قيد التطوير",
    "taskPlan.filterByProject": "تصفية حسب المشروع",
    "taskPlan.searchRequirements": "البحث في المتطلبات...",
    "taskPlan.noRequirements": "لم يتم العثور على متطلبات",
    "taskPlan.noRequirementsDesc": "لا توجد متطلبات تطابق المرشحات الحالية",
    "taskPlan.selectProject": "اختيار مشروع",
    "taskPlan.allProjects": "جميع المشاريع",
    "taskPlan.showingResults": "عرض {total} متطلب",
    "taskPlan.project": "المشروع",
    "taskPlan.requirementName": "المتطلب",
    "taskPlan.priority": "الأولوية",
    "taskPlan.status": "الحالة",
    "taskPlan.dueDate": "تاريخ الاستحقاق",
    "taskPlan.actions": "الإجراءات",

    // Timeline Validation Messages
    "validation.nameRequired": "الاسم مطلوب",
    "validation.nameMinLength": "يجب أن يكون الاسم على الأقل حرفين",
    "validation.startDateRequired": "تاريخ البداية مطلوب",
    "validation.endDateRequired": "تاريخ النهاية مطلوب",
    "validation.endDateAfterStart":
      "يجب أن يكون تاريخ النهاية بعد تاريخ البداية",

    // User Management
    "users.title": "إدارة المستخدمين",
    "users.subtitle": "إدارة مستخدمي النظام والأدوار والصلاحيات",
    "users.addUser": "إضافة مستخدم جديد",
    "users.editUser": "تحرير المستخدم",
    "users.deleteUser": "حذف المستخدم",
    "users.userName": "اسم المستخدم",
    "users.fullName": "الاسم الكامل",
    "users.militaryNumber": "الرقم العسكري",
    "users.gradeName": "الرتبة",
    "users.roles": "الأدوار",
    "users.actions": "الصلاحيات",
    "users.isVisible": "نشط",
    "users.status": "الحالة",
    "users.searchEmployees":
      "البحث عن الموظفين بالاسم أو الرقم العسكري أو اسم المستخدم",
    "users.noEmployeesFound": "لم يتم العثور على موظفين",
    "users.selectEmployee": "اختر موظف",
    "users.employeeNotFound": "لم يتم العثور على الموظف",
    "users.assignRoles": "تعيين دور",
    "users.assignActions": "تعيين الصلاحيات",
    "users.assignAdditionalActions": "تعيين صلاحيات إضافية",
    "users.permissionsSummary": "ملخص الصلاحيات",
    "users.confirmDelete": "تأكيد حذف المستخدم",
    "users.deleteConfirmMessage": "هل أنت متأكد من حذف هذا المستخدم؟",
    "users.userStats": "إحصائيات المستخدمين",
    "users.totalUsers": "إجمالي المستخدمين",
    "users.activeUsers": "المستخدمون النشطون",
    "users.inactiveUsers": "المستخدمون غير النشطين",
    "users.usersByRole": "المستخدمون حسب الدور",
    "users.accountStatus": "حالة الحساب",
    "users.activeDescription": "المستخدم نشط ويمكنه الوصول للنظام",
    "users.inactiveDescription": "المستخدم غير نشط ولا يمكنه الوصول للنظام",

    // Department Management
    "departments.title": "إدارة الأقسام",
    "departments.subtitle": "إدارة الأقسام التنظيمية وأعضائها",
    "departments.addDepartment": "إضافة قسم جديد",
    "departments.editDepartment": "تحرير القسم",
    "departments.deleteDepartment": "حذف القسم",
    "departments.viewMembers": "عرض الأعضاء",
    "departments.manageMembers": "إدارة الأعضاء",
    "departments.name": "اسم القسم",
    "departments.nameAr": "الاسم بالعربية",
    "departments.status": "الحالة",
    "departments.description": "الوصف",
    "departments.memberCount": "عدد الأعضاء",
    "departments.createdAt": "تاريخ الإنشاء",
    "departments.updatedAt": "آخر تحديث",
    "departments.actions": "الإجراءات",
    "departments.active": "نشط",
    "departments.inactive": "غير نشط",
    "departments.searchDepartments": "البحث في الأقسام...",
    "departments.noDepartmentsFound": "لا توجد أقسام",
    "departments.confirmDelete": "تأكيد حذف القسم",
    "departments.deleteConfirmMessage": "هل أنت متأكد من حذف هذا القسم؟",
    "departments.deleteWarning": "سيتم إزالة جميع الأعضاء من هذا القسم.",
    "departments.fillDepartmentDetails": "املأ تفاصيل القسم أدناه",
    "departments.updateDepartmentInfo": "تحديث معلومات القسم",

    // Department Members
    "departments.members.title": "أعضاء القسم",
    "departments.members.addMember": "إضافة عضو",
    "departments.members.editMember": "تحرير العضو",
    "departments.members.removeMember": "إزالة العضو",
    "departments.members.searchEmployee": "البحث عن موظف",
    "departments.members.manualEntry": "إدخال يدوي",
    "departments.members.selectEmployee": "اختر موظفاً",
    "departments.members.employeeNotFound":
      "لم يتم العثور على الموظف؟ يمكنك الإضافة يدوياً",
    "departments.members.userName": "اسم المستخدم",
    "departments.members.fullName": "الاسم الكامل",
    "departments.members.militaryNumber": "الرقم العسكري",
    "departments.members.gradeName": "الرتبة",
    "departments.members.role": "الدور",
    "departments.members.joinedAt": "تاريخ الانضمام",
    "departments.members.isActive": "نشط",
    "departments.members.manager": "مدير",
    "departments.members.supervisor": "مشرف",
    "departments.members.member": "عضو",
    "departments.members.noMembersFound": "لا توجد أعضاء في هذا القسم",
    "departments.members.confirmRemove": "تأكيد إزالة العضو",
    "departments.members.removeConfirmMessage":
      "هل أنت متأكد من إزالة هذا العضو من القسم؟",
    "departments.members.searchPlaceholder":
      "البحث بالاسم أو الرقم العسكري أو اسم المستخدم",

    // Department Statistics
    "departments.stats.title": "إحصائيات الأقسام",
    "departments.stats.totalDepartments": "إجمالي الأقسام",
    "departments.stats.activeDepartments": "الأقسام النشطة",
    "departments.stats.inactiveDepartments": "الأقسام غير النشطة",
    "departments.stats.totalMembers": "إجمالي الأعضاء",

    // Units Management
    "units.title": "إدارة الوحدات",
    "units.subtitle": "إدارة التسلسل الهرمي للوحدات التنظيمية",
    "units.selectUnit": "اختيار وحدة",
    "units.searchUnits": "البحث في الوحدات...",
    "units.noUnits": "لا توجد وحدات",
    "units.noSearchResults": "لم يتم العثور على وحدات مطابقة لبحثك",
    "units.expandAll": "توسيع الكل",
    "units.collapseAll": "طي الكل",
    "units.unitPath": "مسار الوحدة",
    "units.selectedPath": "مسار الوحدة المحددة",
    "units.selected": "محدد",
    "units.level": "المستوى",
    "units.code": "رمز الوحدة",
    "units.name": "اسم الوحدة",
    "units.nameAr": "الاسم العربي",
    "units.description": "الوصف",
    "units.parentUnit": "الوحدة الرئيسية",
    "units.childUnits": "الوحدات الفرعية",
    "units.isActive": "نشط",
    "units.inactive": "غير نشط",

    // Roles
    "roles.title": "إدارة الأدوار",
    "roles.name": "اسم الدور",
    "roles.description": "الوصف",
    "roles.active": "نشط",
    "roles.order": "الترتيب",
    "roles.permissions": "الصلاحيات",
    "roles.assignActions": "تعيين الصلاحيات",
    "roles.selectRole": "اختر دوراً",
    "roles.role": "الدور",

    // Actions/Permissions
    "actions.title": "إدارة الصلاحيات",
    "actions.name": "اسم الصلاحية",
    "actions.category": "الفئة",
    "actions.description": "الوصف",
    "actions.userManagement": "إدارة المستخدمين",
    "actions.projectManagement": "إدارة المشاريع",
    "actions.roleManagement": "إدارة الأدوار",
    "actions.systemAdmin": "إدارة النظام",
    "actions.defaultActions": "صلاحيات افتراضية",
    "actions.defaultActionsForRole": "الصلاحيات الافتراضية للدور",
    "actions.defaultActionsNote":
      "هذه الصلاحيات تُمنح تلقائياً مع هذا الدور ولا يمكن إزالتها.",
    "actions.totalActions": "إجمالي الصلاحيات",
    "actions.defaultFromRole": "افتراضية من الدور",
    "actions.additionalSelected": "مختارة إضافياً",
    "actions.scrollToSeeMore": "مرر لرؤية المزيد من الفئات",
    "actions.totalAvailable": "صلاحية متاحة إجمالاً",
    "actions.selected": "مختارة",
    "actions.selectActions": "اختيار الصلاحيات",
    "actions.selectAdditionalActions": "اختيار صلاحيات إضافية",
    "actions.selectAdditionalActionsDescription":
      "اختر صلاحيات إضافية تتجاوز الصلاحيات الافتراضية للدور",
    "actions.searchActions": "البحث في الصلاحيات...",
    "actions.allCategories": "جميع الفئات",
    "actions.actionsSelected": "صلاحية مختارة",
    "actions.availableActions": "صلاحيات متاحة",
    "actions.clearAll": "مسح الكل",
    "actions.selectAll": "اختيار الكل",
    "actions.selectNone": "عدم اختيار أي",
    "actions.noActionsFound": "لم يتم العثور على صلاحيات تطابق المعايير",
    "actions.noAdditionalActionsAvailable": "لا توجد صلاحيات إضافية متاحة",
    "actions.confirmSelection": "تأكيد الاختيار",
    "actions.additionalActionsSelected": "صلاحية إضافية مختارة",
    "actions.noAdditionalActionsSelected": "لم يتم اختيار صلاحيات إضافية",

    // Permissions
    "permissions.create": "إنشاء",
    "permissions.read": "قراءة",
    "permissions.update": "تحديث",
    "permissions.delete": "حذف",
    "permissions.admin": "مدير النظام",
    "permissions.denied": "الوصول مرفوض",
    "permissions.insufficient": "صلاحيات غير كافية لتنفيذ هذا الإجراء",

    // Access Denied
    "access.denied.title": "الوصول مرفوض",
    "access.denied.message": "ليس لديك صلاحية للوصول إلى هذا المشروع.",
    "access.denied.loading": "جاري التحميل...",

    // Project Status Options
    // Project Status/Phases
    "projectStatus.1": "قيد الدراسة",
    "projectStatus.2": "قيد التطوير",
    "projectStatus.3": "بيئة الفحص",
    "projectStatus.4": "بيئة التشغيل",
    "projectStatus.5": "بيئة الانتاج",

    // Timeline
    "timeline.title": "إدارة المخطط الزمني",
    "timeline.subtitle":
      "إدارة الجداول الزمنية للمشاريع والسبرينتات والمتطلبات والمهام",
    "timeline.newTimeline": "جدول زمني جديد",
    "timeline.filters": "المرشحات",
    "timeline.refresh": "تحديث",
    "timeline.selectProjectTimeline": "اختر المشروع والمخطط الزمني",
    "timeline.chooseProjectTimeline": "اختر مشروعاً وجدولاً زمنياً",
    "timeline.loadingProjects": "جاري تحميل المشاريع...",
    "timeline.noProjectsAvailable": "لا توجد مشاريع متاحة",
    "timeline.loadingTimelines": "جاري تحميل الجداول الزمنية...",
    "timeline.noTimelines":
      'لا توجد جداول زمنية - انقر "جدول زمني جديد" لإنشاء واحد',
    "timeline.sprints": "السبرينتات",
    "timeline.sprint": "سبرينت",
    "timeline.requirements": "المتطلبات",
    "timeline.requirement": "متطلب",
    "timeline.tasks": "المهام",
    "timeline.task": "مهمة",
    "timeline.subtasks": "المهام الفرعية",
    "timeline.subtask": "مهمة فرعية",
    "timeline.assignedMembers": "الأعضاء المخصصون",
    "timeline.searchPlaceholder":
      "البحث في الجداول الزمنية، السبرينتات، المتطلبات...",
    "timeline.noTimelinesFound": "لم يتم العثور على جداول زمنية",
    "timeline.noTimelinesDescription":
      "هذا المشروع لا يحتوي على أي جداول زمنية بعد.",
    "timeline.noTimelinesGeneral":
      "اختر مشروعاً وأنشئ جدولك الزمني الأول للبدء.",
    "timeline.createTimeline": "إنشاء جدول زمني",
    "timeline.selectTimeline": "اختر جدولاً زمنياً",
    "timeline.selectTimelineDescription":
      "اختر جدولاً زمنياً من القائمة المنسدلة أعلاه لعرض تفاصيله.",
    "timeline.ganttView": "عرض غانت",
    "timeline.treeView": "العرض الشجري",
    "timeline.details": "التفاصيل",
    "timeline.timelineFilters": "مرشحات المخطط الزمني",
    "timeline.clearAll": "مسح الكل",
    "timeline.applyFilters": "تطبيق المرشحات",
    "timeline.autoSelectingFirst": "اختيار تلقائي للجدول الزمني الأول للمشروع",
    "timeline.loading": "جاري التحميل...",

    // Timeline Create Modal
    "timeline.createModal.title": "إنشاء جدول زمني",
    "timeline.createModal.editTitle": "تحرير المخطط الزمني",
    "timeline.createModal.name": "اسم المخطط الزمني",
    "timeline.createModal.description": "الوصف",
    "timeline.createModal.startDate": "تاريخ البداية",
    "timeline.createModal.endDate": "تاريخ النهاية",
    "timeline.createModal.cancel": "إلغاء",
    "timeline.createModal.save": "حفظ المخطط الزمني",
    "timeline.createModal.update": "تحديث المخطط الزمني",
    "timeline.createModal.nameRequired": "اسم المخطط الزمني مطلوب",
    "timeline.createModal.startDateRequired": "تاريخ البداية مطلوب",
    "timeline.createModal.endDateRequired": "تاريخ النهاية مطلوب",
    "timeline.createModal.endDateMustBeAfter":
      "تاريخ النهاية يجب أن يكون بعد تاريخ البداية",
    "timeline.createModal.projectIdRequired": "معرف المشروع مطلوب",

    // Timeline TreeView
    "timeline.treeView.addSprint": "إضافة سبرينت",
    "timeline.treeView.addRequirement": "إضافة متطلب",
    "timeline.treeView.addTask": "إضافة مهمة",
    "timeline.treeView.addSubtask": "إضافة مهمة فرعية",
    "timeline.treeView.create": "إنشاء",
    "timeline.treeView.edit": "تحرير",
    "timeline.treeView.delete": "حذف",
    "timeline.treeView.editSprint": "تحرير السبرينت",
    "timeline.treeView.deleteSprint": "حذف السبرينت",
    "timeline.treeView.editRequirement": "تحرير المتطلب",
    "timeline.treeView.deleteRequirement": "حذف المتطلب",
    "timeline.treeView.editTask": "تحرير المهمة",
    "timeline.treeView.deleteTask": "حذف المهمة",
    "timeline.treeView.moveTask": "نقل المهمة",
    "timeline.treeView.editSubtask": "تحرير المهمة الفرعية",
    "timeline.treeView.deleteSubtask": "حذف المهمة الفرعية",
    "timeline.treeView.confirmDelete": "هل أنت متأكد من حذف هذا",
    "timeline.treeView.cancel": "إلغاء",
    "timeline.treeView.saveChanges": "حفظ التغييرات",
    "timeline.treeView.editModalTitle": "تحرير",
    "timeline.treeView.name": "الاسم",
    "timeline.treeView.description": "الوصف",
    "timeline.treeView.startDate": "تاريخ البداية",
    "timeline.treeView.endDate": "تاريخ النهاية",
    "timeline.treeView.department": "القسم",
    "timeline.treeView.assignedTo": "مُعين إلى",
    "timeline.treeView.status": "الحالة",
    "timeline.treeView.priority": "الأولوية",
    "timeline.treeView.progress": "التقدم",
    "timeline.treeView.notes": "ملاحظات إضافية",
    "timeline.treeView.sprintsLabel": "السبرينتات",
    "timeline.treeView.requirementsLabel": "المتطلبات",
    "timeline.treeView.tasksLabel": "المهام",
    "timeline.treeView.subtasksLabel": "المهام الفرعية",
    "timeline.treeView.timelineLabel": "المخطط الزمني",
    "timeline.treeView.progressColorLegend": "مفتاح ألوان التقدم",
    "timeline.treeView.hierarchyColorLegend": "مفتاح ألوان التسلسل الهرمي",
    "timeline.treeView.progressCritical": "0-25% (حرج)",
    "timeline.treeView.progressBehind": "26-50% (متأخر)",
    "timeline.treeView.progressOnTrack": "51-75% (على المسار)",
    "timeline.treeView.progressExcellent": "76-100% (ممتاز)",
    "timeline.treeView.loadingTimeline": "جاري تحميل المخطط الزمني...",
    "timeline.treeView.searchPlaceholder":
      "البحث في السبرينتات والمتطلبات والمهام...",
    "timeline.treeView.filtered": "مفلتر",

    // Timeline Move Task Modal
    "timeline.moveTask.title": "نقل المهمة",
    "timeline.moveTask.subtitle": 'نقل "{taskName}" بعدد الأيام المحدد',
    "timeline.moveTask.quickMoveOptions": "خيارات النقل السريع",
    "timeline.moveTask.customMove": "نقل مخصص",
    "timeline.moveTask.movePlus1Day": "تقدم يوم واحد",
    "timeline.moveTask.moveMinus1Day": "تأخير يوم واحد",
    "timeline.moveTask.movePlus1Week": "تقدم أسبوع واحد",
    "timeline.moveTask.moveMinus1Week": "تأخير أسبوع واحد",
    "timeline.moveTask.enterDays": "أدخل الأيام (مثال: 5، -3)",
    "timeline.moveTask.daysDescription":
      "الأرقام الموجبة للتقدم، السالبة للتأخير",
    "timeline.moveTask.move": "نقل",
    "timeline.moveTask.cancel": "إلغاء",
    "timeline.moveTask.successMessage": "تم نقل المهمة بنجاح بـ {days} أيام",
    "timeline.moveTask.errorMessage": "فشل في نقل المهمة",
    "timeline.moveTask.invalidDays": "يرجى إدخال عدد صحيح من الأيام",

    // Timeline Move Requirement Modal
    "timeline.moveRequirement.title": "نقل المتطلب",
    "timeline.moveRequirement.subtitle": "نقل هذا المتطلب إلى سبرينت آخر",
    "timeline.moveRequirement.currentRequirement": "المتطلب الحالي",
    "timeline.moveRequirement.currentSprint": "السبرينت الحالي",
    "timeline.moveRequirement.selectTargetSprint": "اختر السبرينت المستهدف",
    "timeline.moveRequirement.selectSprint": "اختر سبرينت...",
    "timeline.moveRequirement.searchSprints": "البحث في السبرينتات...",
    "timeline.moveRequirement.noSprintsAvailable":
      "لا توجد سبرينتات أخرى متاحة",
    "timeline.moveRequirement.moveSummary": "ملخص النقل",
    "timeline.moveRequirement.movingRequirement": "نقل المتطلب",
    "timeline.moveRequirement.fromSprint": "من السبرينت",
    "timeline.moveRequirement.toSprint": "إلى السبرينت",
    "timeline.moveRequirement.moveButton": "نقل المتطلب",
    "timeline.moveRequirement.moving": "جاري النقل...",
    "timeline.moveRequirement.success": "نجح!",
    "timeline.moveRequirement.successMessage": "تم نقل المتطلب بنجاح",
    "timeline.treeView.moveRequirement": "نقل المتطلب",

    // Move Task Between Requirements translations (Arabic)
    "timeline.moveTaskToRequirement.title": "نقل المهمة",
    "timeline.moveTaskToRequirement.subtitle": "نقل هذه المهمة إلى متطلب آخر",
    "timeline.moveTaskToRequirement.currentTask": "المهمة الحالية",
    "timeline.moveTaskToRequirement.currentRequirement": "المتطلب الحالي",
    "timeline.moveTaskToRequirement.selectTargetRequirement":
      "اختر المتطلب المستهدف",
    "timeline.moveTaskToRequirement.selectRequirement": "اختر متطلباً...",
    "timeline.moveTaskToRequirement.searchRequirements":
      "البحث في المتطلبات...",
    "timeline.moveTaskToRequirement.noRequirementsAvailable":
      "لا توجد متطلبات أخرى متاحة",
    "timeline.moveTaskToRequirement.moveSummary": "ملخص النقل",
    "timeline.moveTaskToRequirement.movingTask": "نقل المهمة",
    "timeline.moveTaskToRequirement.fromRequirement": "من المتطلب",
    "timeline.moveTaskToRequirement.toRequirement": "إلى المتطلب",
    "timeline.moveTaskToRequirement.moveButton": "نقل المهمة",
    "timeline.moveTaskToRequirement.moving": "جاري النقل...",
    "timeline.moveTaskToRequirement.success": "نجح!",
    "timeline.moveTaskToRequirement.successMessage": "تم نقل المهمة بنجاح",
    "timeline.treeView.moveTaskToRequirement": "نقل المهمة",

    // Timeline TreeView Additional Keys (Arabic)
    "timeline.treeView.moveTaskToSprint": "نقل المهمة إلى سبرينت",
    "timeline.treeView.currentTask": "المهمة الحالية",
    "timeline.treeView.currentSprint": "السبرينت الحالي",
    "timeline.treeView.selectTargetSprint": "اختر السبرينت المستهدف",
    "timeline.treeView.selectSprint": "اختر سبرينت...",

    "timeline.filters.search": "البحث",
    "timeline.filters.searchPlaceholder":
      "البحث في الجداول الزمنية والسبرينتات والمتطلبات والمهام...",
    "timeline.filters.activeFilters": "المرشحات النشطة",
    "timeline.filters.clearAll": "مسح الكل",
    "timeline.filters.dept": "القسم",
    "timeline.filters.member": "العضو",
    "timeline.filters.status": "الحالة",
    "timeline.filters.priority": "الأولوية",
    "timeline.filters.departments": "الأقسام",
    "timeline.filters.assignedUsers": "المستخدمون المخصصون",
    "timeline.filters.searchUsers": "البحث عن المستخدمين...",
    "timeline.filters.taskStatus": "حالة المهمة",
    "timeline.filters.taskPriority": "أولوية المهمة",
    "timeline.filters.unavailable": "غير متاح",
    "timeline.filters.notStarted": "لم تبدأ",
    "timeline.filters.inProgress": "قيد التنفيذ",
    "timeline.filters.completed": "مكتملة",
    "timeline.filters.onHold": "معلقة",
    "timeline.filters.cancelled": "ملغية",
    "timeline.filters.low": "منخفضة",
    "timeline.filters.medium": "متوسطة",
    "timeline.filters.high": "عالية",
    "timeline.filters.critical": "حرجة",
    "timeline.create.title": "إنشاء جدول زمني جديد",
    "timeline.create.subtitle": "قم بإنشاء جدول زمني جديد لتنظيم مراحل مشروعك",
    "timeline.create.timelineName": "اسم المخطط الزمني",
    "timeline.create.timelineNamePlaceholder": "أدخل اسم المخطط الزمني",
    "timeline.create.description": "الوصف",
    "timeline.create.descriptionPlaceholder": "وصف هذا المخطط الزمني (اختياري)",
    "timeline.create.startDate": "تاريخ البداية",
    "timeline.create.endDate": "تاريخ النهاية",
    "timeline.create.noProjectWarning":
      "تحذير: لم يتم تحديد مشروع. يرجى تحديد مشروع أولاً.",
    "timeline.create.cancel": "إلغاء",
    "timeline.create.createTimeline": "إنشاء المخطط الزمني",
    "timeline.create.nameRequired": "اسم المخطط الزمني مطلوب",
    "timeline.create.startDateRequired": "تاريخ البداية مطلوب",
    "timeline.create.endDateRequired": "تاريخ النهاية مطلوب",
    "timeline.create.endDateAfterStart":
      "يجب أن يكون تاريخ النهاية بعد تاريخ البداية",
    "timeline.create.projectRequired": "معرف المشروع مطلوب",
    "timeline.create.failedToCreate": "فشل في إنشاء المخطط الزمني",
    "timeline.pageTitle": "المخطط الزمني للمشروع",
    "timeline.pageDescription":
      "إدارة الجداول الزمنية للمشروع والسبرينتات والمتطلبات والمهام",

    // Timeline Details Panel
    "timeline.detailsPanel.noItemSelected": "لم يتم اختيار عنصر",
    "timeline.detailsPanel.selectAnItem": "اختر عنصراً من الشجرة لعرض تفاصيله",
    "timeline.detailsPanel.overview": "نظرة عامة",
    "timeline.detailsPanel.description": "الوصف",
    "timeline.detailsPanel.startDate": "تاريخ البداية",
    "timeline.detailsPanel.endDate": "تاريخ النهاية",
    "timeline.detailsPanel.duration": "المدة",
    "timeline.detailsPanel.days": "أيام",
    "timeline.detailsPanel.status": "الحالة",
    "timeline.detailsPanel.priority": "الأولوية",
    "timeline.detailsPanel.progress": "التقدم",
    "timeline.detailsPanel.department": "القسم",
    "timeline.detailsPanel.selectDepartment": "اختر القسم",
    "timeline.detailsPanel.assignedTo": "مُعين إلى",
    "timeline.detailsPanel.edit": "تحرير",
    "timeline.detailsPanel.cancel": "إلغاء",
    "timeline.detailsPanel.saveChanges": "حفظ التغييرات",
    "timeline.detailsPanel.projectId": "معرف المشروع",
    "timeline.detailsPanel.structure": "الهيكل",
    "timeline.detailsPanel.tasks": "المهام",
    "timeline.detailsPanel.subtasks": "المهام الفرعية",
    "timeline.detailsPanel.statusAndPriority": "الحالة والأولوية",
    "timeline.detailsPanel.additionalNotes": "ملاحظات إضافية",
    "timeline.detailsPanel.estimated": "المقدر",
    "timeline.detailsPanel.actual": "الفعلي",
    "timeline.detailsPanel.selectStatus": "اختر الحالة",
    "timeline.detailsPanel.selectPriority": "اختر الأولوية",
    "timeline.chooseTask": "اختر مهمة",
    "timeline.selectPredecessors": "اختر المهام السابقة",
    "timeline.selectPredecessorsPlaceholder": "اختر مهمة سابقة...",
    "timeline.searchTask": "البحث عن مهمة",
    "timeline.taskName": "اسم المهمة",
    "timeline.startDate": "تاربخ البدء",
    "timeline.duration": "المدة",
    "timelane.back": "العودة",
    "timeline.month": "شهر",
    "timeline.day": "يوم",
    "timeline.week": "أسبوع",
    "timeline.year": "سنة",
    "timeline.normalSize": "حجم عادي",
    "timeline.largeSize": "حجم أكبر",
    "timeline.controlCellHeight": "تحكم بالحجم",
    "timeline.gantt.description": "الوصف",
    "timeline.gantt.period": "المدة",
    "timeline.gantt.save": "حفظ",
    "timeline.gantt.cancel": "إلغاء",
    "timeline.gantt.delete": "حذف",
    "timeline.gantt.progress": "ما تم انجازه",
    "timeline.gantt.editTask": "تعديل المهمة",
    // Members Tasks Dashboard
    membersTasksDashboard: "لوحة مهام الأعضاء",
    tasksOverview: "نظرة عامة على المهام",

    // Filters
    filterByAssignees: "تصفية حسب المعينين",
    filterByDepartment: "تصفية حسب القسم",
    filterByStatus: "تصفية حسب الحالة",
    filterByPriority: "تصفية حسب الأولوية",
    filterByDateRange: "تصفية حسب النطاق الزمني",
    showOverdueOnly: "إظهار المتأخرة فقط",
    anyAssigneeMode: "المهام مع أي من المعينين المحددين",
    allAssigneesMode: "المهام مع جميع المعينين المحددين",
    clearAllFilters: "مسح جميع المرشحات",
    activeFilters: "المرشحات النشطة",

    // Task Card
    primaryAssignee: "المعين الأساسي",
    otherAssignees: "المعينون الآخرون",
    moreAssignees: "معين إضافي",
    taskProgress: "التقدم",
    timeSpent: "الوقت المستغرق",
    estimatedTime: "الوقت المقدر",
    taskTags: "العلامات",
    overdueTask: "متأخر",
    taskDetails: "تفاصيل المهمة",

    // Export
    exportTasks: "تصدير المهام",
    exportAsCSV: "تصدير كـ CSV",
    exportAsPDF: "تصدير كـ PDF",
    exportAsExcel: "تصدير كـ Excel",

    // States
    noTasksFound: "لم يتم العثور على مهام",
    adjustFiltersMessage: "حاول تعديل المرشحات لرؤية المزيد من النتائج",
    loadingTasks: "جاري تحميل المهام...",
    errorLoadingTasks: "خطأ في تحميل المهام",
    selectDepartment: "اختر القسم",
    selectStatus: "اختر الحالة",
    selectPriority: "اختر الأولوية",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("ar"); // Default to Arabic
  const direction: Direction = language === "ar" ? "rtl" : "ltr";

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = lang;
  };

  const t = (key: string): string => {
    return (
      translations[language][
        key as keyof (typeof translations)[typeof language]
      ] || key
    );
  };

  useEffect(() => {
    // Check for saved language preference first
    const savedLanguage = localStorage.getItem("language") as Language;

    if (savedLanguage && (savedLanguage === "en" || savedLanguage === "ar")) {
      setLanguageState(savedLanguage); // Use setLanguageState to avoid infinite loop
      document.documentElement.dir = savedLanguage === "ar" ? "rtl" : "ltr";
      document.documentElement.lang = savedLanguage;
    } else {
      // Default to Arabic if no saved preference
      setLanguageState("ar");
      localStorage.setItem("language", "ar");
      document.documentElement.dir = "rtl";
      document.documentElement.lang = "ar";
    }
  }, []);

  // Handle language changes and update document direction
  useEffect(() => {
    localStorage.setItem("language", language);
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, direction, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);

  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }

  return context;
}
